'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class AssocierCompte

    Protected WithEvents ucEtapes As Global.MngConsul.EtapesReprise

    Protected WithEvents hfCle As Global.System.Web.UI.WebControls.HiddenField

    Protected WithEvents litProgres As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents pnlCarte As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents litCarte As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents btnPlusTard As Global.System.Web.UI.WebControls.Button

    Protected WithEvents btnCabinet As Global.System.Web.UI.WebControls.Button

    Protected WithEvents btnAssocier As Global.System.Web.UI.WebControls.Button

    Protected WithEvents pnlFin As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents litFin As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents btnReprendre As Global.System.Web.UI.WebControls.Button
End Class
