'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>litFirstName control.</summary>
    Protected WithEvents litFirstName As Global.System.Web.UI.WebControls.Literal

    '''<summary>litPlanName control.</summary>
    Protected WithEvents litPlanName As Global.System.Web.UI.WebControls.Literal

    '''<summary>litTrialEnd control.</summary>
    Protected WithEvents litTrialEnd As Global.System.Web.UI.WebControls.Literal

    '''<summary>litKpiCustomers control.</summary>
    Protected WithEvents litKpiCustomers As Global.System.Web.UI.WebControls.Literal

    '''<summary>litKpiSupplierInvoices control.</summary>
    Protected WithEvents litKpiSupplierInvoices As Global.System.Web.UI.WebControls.Literal

    '''<summary>litKpiProducts control.</summary>
    Protected WithEvents litKpiProducts As Global.System.Web.UI.WebControls.Literal

    '''<summary>litKpiRevenue control.</summary>
    Protected WithEvents litKpiRevenue As Global.System.Web.UI.WebControls.Literal
End Class
