'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ImportPlanComptable

    '''<summary>pnlSucces</summary>
    Protected WithEvents pnlSucces As Global.System.Web.UI.WebControls.Panel
    '''<summary>litSucces</summary>
    Protected WithEvents litSucces As Global.System.Web.UI.WebControls.Literal
    '''<summary>pnlAvertissement</summary>
    Protected WithEvents pnlAvertissement As Global.System.Web.UI.WebControls.Panel
    '''<summary>litAvertissement</summary>
    Protected WithEvents litAvertissement As Global.System.Web.UI.WebControls.Literal
    '''<summary>pnlErreur</summary>
    Protected WithEvents pnlErreur As Global.System.Web.UI.WebControls.Panel
    '''<summary>litErreur</summary>
    Protected WithEvents litErreur As Global.System.Web.UI.WebControls.Literal

    '''<summary>ddlSysteme</summary>
    Protected WithEvents ddlSysteme As Global.System.Web.UI.WebControls.DropDownList
    '''<summary>ddlSeparateur</summary>
    Protected WithEvents ddlSeparateur As Global.System.Web.UI.WebControls.DropDownList
    '''<summary>ddlEncodage</summary>
    Protected WithEvents ddlEncodage As Global.System.Web.UI.WebControls.DropDownList
    '''<summary>litNomSysteme</summary>
    Protected WithEvents litNomSysteme As Global.System.Web.UI.WebControls.Literal
    '''<summary>litCheminExport</summary>
    Protected WithEvents litCheminExport As Global.System.Web.UI.WebControls.Literal

    '''<summary>fuFichier</summary>
    Protected WithEvents fuFichier As Global.System.Web.UI.WebControls.FileUpload
    '''<summary>chkEntete</summary>
    Protected WithEvents chkEntete As Global.System.Web.UI.WebControls.CheckBox
    '''<summary>btnApercu</summary>
    Protected WithEvents btnApercu As Global.System.Web.UI.WebControls.Button
    '''<summary>btnCharger</summary>
    Protected WithEvents btnCharger As Global.System.Web.UI.WebControls.Button

    '''<summary>pnlApercu</summary>
    Protected WithEvents pnlApercu As Global.System.Web.UI.WebControls.Panel
    '''<summary>litApercuInfo</summary>
    Protected WithEvents litApercuInfo As Global.System.Web.UI.WebControls.Literal
    '''<summary>litCorrespondance</summary>
    Protected WithEvents litCorrespondance As Global.System.Web.UI.WebControls.Literal
    '''<summary>gvApercu</summary>
    Protected WithEvents gvApercu As Global.System.Web.UI.WebControls.GridView

    '''<summary>pnlResultat</summary>
    Protected WithEvents pnlResultat As Global.System.Web.UI.WebControls.Panel
    '''<summary>litLues</summary>
    Protected WithEvents litLues As Global.System.Web.UI.WebControls.Literal
    '''<summary>litRetenues</summary>
    Protected WithEvents litRetenues As Global.System.Web.UI.WebControls.Literal
    '''<summary>litAnomalies</summary>
    Protected WithEvents litAnomalies As Global.System.Web.UI.WebControls.Literal

    '''<summary>pnlLignes</summary>
    Protected WithEvents pnlLignes As Global.System.Web.UI.WebControls.Panel
    '''<summary>ddlFiltre</summary>
    Protected WithEvents ddlFiltre As Global.System.Web.UI.WebControls.DropDownList
    '''<summary>gvLignes</summary>
    Protected WithEvents gvLignes As Global.System.Web.UI.WebControls.GridView

    '''<summary>pnlLots</summary>
    Protected WithEvents pnlLots As Global.System.Web.UI.WebControls.Panel
    '''<summary>gvLots</summary>
    Protected WithEvents gvLots As Global.System.Web.UI.WebControls.GridView

End Class
