'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class ImportProduits

    '''<summary>ucImport</summary>
    Protected WithEvents ucImport As Global.MngConsul.ImportDonnees
End Class