'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class ImportBalanceVerification

    '''<summary>pnlSuccess</summary>
    Protected WithEvents pnlSuccess As Global.System.Web.UI.WebControls.Panel

    '''<summary>litSuccess</summary>
    Protected WithEvents litSuccess As Global.System.Web.UI.WebControls.Literal

    '''<summary>pnlError</summary>
    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel

    '''<summary>litError</summary>
    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal

    '''<summary>pnlWarning</summary>
    Protected WithEvents pnlWarning As Global.System.Web.UI.WebControls.Panel

    '''<summary>litWarning</summary>
    Protected WithEvents litWarning As Global.System.Web.UI.WebControls.Literal

    '''<summary>pnlResults</summary>
    Protected WithEvents pnlResults As Global.System.Web.UI.WebControls.Panel

    '''<summary>litTitreResultat</summary>
    Protected WithEvents litTitreResultat As Global.System.Web.UI.WebControls.Literal

    '''<summary>litOrigine</summary>
    Protected WithEvents litOrigine As Global.System.Web.UI.WebControls.Literal

    '''<summary>pnlStats</summary>
    Protected WithEvents pnlStats As Global.System.Web.UI.WebControls.Panel

    '''<summary>litInserted</summary>
    Protected WithEvents litInserted As Global.System.Web.UI.WebControls.Literal

    '''<summary>litSkipped</summary>
    Protected WithEvents litSkipped As Global.System.Web.UI.WebControls.Literal

    '''<summary>litErrors</summary>
    Protected WithEvents litErrors As Global.System.Web.UI.WebControls.Literal

    '''<summary>pnlControle</summary>
    Protected WithEvents pnlControle As Global.System.Web.UI.WebControls.Panel

    '''<summary>litControle</summary>
    Protected WithEvents litControle As Global.System.Web.UI.WebControls.Literal

    '''<summary>pnlBalance</summary>
    Protected WithEvents pnlBalance As Global.System.Web.UI.WebControls.Panel

    '''<summary>litEquilibre</summary>
    Protected WithEvents litEquilibre As Global.System.Web.UI.WebControls.Literal

    '''<summary>litBalance</summary>
    Protected WithEvents litBalance As Global.System.Web.UI.WebControls.Literal

    '''<summary>pnlErrorDetails</summary>
    Protected WithEvents pnlErrorDetails As Global.System.Web.UI.WebControls.Panel

    '''<summary>gvErrors</summary>
    Protected WithEvents gvErrors As Global.System.Web.UI.WebControls.GridView

    '''<summary>btnControle</summary>
    Protected WithEvents btnControle As Global.System.Web.UI.WebControls.Button

    '''<summary>btnReset</summary>
    Protected WithEvents btnReset As Global.System.Web.UI.WebControls.Button

    '''<summary>btnTruncateTable</summary>
    Protected WithEvents btnTruncateTable As Global.System.Web.UI.WebControls.Button

    '''<summary>ucSource</summary>
    Protected WithEvents ucSource As Global.MngConsul.SourceDonnees

    '''<summary>pnlUpload</summary>
    Protected WithEvents pnlUpload As Global.System.Web.UI.WebControls.Panel

    '''<summary>fuCsvFile</summary>
    Protected WithEvents fuCsvFile As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>chkTruncate</summary>
    Protected WithEvents chkTruncate As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>btnPreview</summary>
    Protected WithEvents btnPreview As Global.System.Web.UI.WebControls.Button

    '''<summary>btnIA</summary>
    Protected WithEvents btnIA As Global.System.Web.UI.WebControls.Button

    '''<summary>btnImport</summary>
    Protected WithEvents btnImport As Global.System.Web.UI.WebControls.Button

    '''<summary>pnlPreview</summary>
    Protected WithEvents pnlPreview As Global.System.Web.UI.WebControls.Panel

    '''<summary>gvPreview</summary>
    Protected WithEvents gvPreview As Global.System.Web.UI.WebControls.GridView

    '''<summary>litPreviewInfo</summary>
    Protected WithEvents litPreviewInfo As Global.System.Web.UI.WebControls.Literal
End Class
