'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class merci

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''pnlBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents pnlBrand As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''litInitial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litInitial As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLogoImg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litLogoImg As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litCompany As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''pnlAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents pnlAmount As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''litAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litAmount As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''pnlRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRef As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''litRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litRef As Global.System.Web.UI.WebControls.Literal
End Class
