'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class ValiderFactures

    '''<summary>litMsg</summary>
    Protected WithEvents litMsg As Global.System.Web.UI.WebControls.Literal

    '''<summary>ddlType</summary>
    Protected WithEvents ddlType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>btnEnregistrer</summary>
    Protected WithEvents btnEnregistrer As Global.System.Web.UI.WebControls.Button

    '''<summary>btnCreer</summary>
    Protected WithEvents btnCreer As Global.System.Web.UI.WebControls.Button

    '''<summary>btnSupprimer</summary>
    Protected WithEvents btnSupprimer As Global.System.Web.UI.WebControls.Button

    '''<summary>litBilan</summary>
    Protected WithEvents litBilan As Global.System.Web.UI.WebControls.Literal

    '''<summary>litDocs</summary>
    Protected WithEvents litDocs As Global.System.Web.UI.WebControls.Literal
End Class
