'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class ValiderTaxes

    '''<summary>litMsg</summary>
    Protected WithEvents litMsg As Global.System.Web.UI.WebControls.Literal

    '''<summary>litRepere</summary>
    Protected WithEvents litRepere As Global.System.Web.UI.WebControls.Literal

    '''<summary>litInconnus</summary>
    Protected WithEvents litInconnus As Global.System.Web.UI.WebControls.Literal

    '''<summary>litTableau</summary>
    Protected WithEvents litTableau As Global.System.Web.UI.WebControls.Literal

    '''<summary>litTitreForm</summary>
    Protected WithEvents litTitreForm As Global.System.Web.UI.WebControls.Literal

    '''<summary>hfId</summary>
    Protected WithEvents hfId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>txtCode</summary>
    Protected WithEvents txtCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtNom</summary>
    Protected WithEvents txtNom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtTPS</summary>
    Protected WithEvents txtTPS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtTVQ</summary>
    Protected WithEvents txtTVQ As Global.System.Web.UI.WebControls.TextBox

    '''<summary>btnSave</summary>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>btnAnnuler</summary>
    Protected WithEvents btnAnnuler As Global.System.Web.UI.WebControls.Button

    '''<summary>fuFichier</summary>
    Protected WithEvents fuFichier As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>btnImporter</summary>
    Protected WithEvents btnImporter As Global.System.Web.UI.WebControls.Button

    '''<summary>btnRepartir</summary>
    Protected WithEvents btnRepartir As Global.System.Web.UI.WebControls.Button

    '''<summary>litNote</summary>
    Protected WithEvents litNote As Global.System.Web.UI.WebControls.Literal
End Class
