'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class ValiderNonRapprochees

    '''<summary>litRepere</summary>
    Protected WithEvents litRepere As Global.System.Web.UI.WebControls.Literal

    '''<summary>pnlFiltre</summary>
    Protected WithEvents pnlFiltre As Global.System.Web.UI.WebControls.Panel

    '''<summary>chkToutes</summary>
    Protected WithEvents chkToutes As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>litCompteur</summary>
    Protected WithEvents litCompteur As Global.System.Web.UI.WebControls.Literal

    '''<summary>litTableau</summary>
    Protected WithEvents litTableau As Global.System.Web.UI.WebControls.Literal

    '''<summary>litNote</summary>
    Protected WithEvents litNote As Global.System.Web.UI.WebControls.Literal
End Class
