'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class ValiderRecurrentes

    '''<summary>ucApideck</summary>
    Protected WithEvents ucApideck As Global.MngConsul.ImportApideckBouton

    '''<summary>litRepere</summary>
    Protected WithEvents litRepere As Global.System.Web.UI.WebControls.Literal

    '''<summary>litTableau</summary>
    Protected WithEvents litTableau As Global.System.Web.UI.WebControls.Literal

    '''<summary>litNote</summary>
    Protected WithEvents litNote As Global.System.Web.UI.WebControls.Literal
End Class
