'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class ValiderBudgets

    '''<summary>ucApideck</summary>
    Protected WithEvents ucApideck As Global.MngConsul.ImportApideckBouton

    '''<summary>litListe</summary>
    Protected WithEvents litListe As Global.System.Web.UI.WebControls.Literal

    '''<summary>litLignes</summary>
    Protected WithEvents litLignes As Global.System.Web.UI.WebControls.Literal

    '''<summary>litNote</summary>
    Protected WithEvents litNote As Global.System.Web.UI.WebControls.Literal
End Class
