'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class ValiderSociete

    '''<summary>litMsg</summary>
    Protected WithEvents litMsg As Global.System.Web.UI.WebControls.Literal

    '''<summary>litEcarts</summary>
    Protected WithEvents litEcarts As Global.System.Web.UI.WebControls.Literal

    '''<summary>litNouveaux</summary>
    Protected WithEvents litNouveaux As Global.System.Web.UI.WebControls.Literal

    '''<summary>litIdentiques</summary>
    Protected WithEvents litIdentiques As Global.System.Web.UI.WebControls.Literal

    '''<summary>litManquants</summary>
    Protected WithEvents litManquants As Global.System.Web.UI.WebControls.Literal

    '''<summary>btnAppliquer</summary>
    Protected WithEvents btnAppliquer As Global.System.Web.UI.WebControls.Button

    '''<summary>litChamps</summary>
    Protected WithEvents litChamps As Global.System.Web.UI.WebControls.Literal
End Class
