'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfAISale

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''ralp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ralp As Global.Telerik.Web.UI.RadAjaxLoadingPanel

    '''<summary>
    '''hfPeriodeSel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPeriodeSel As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfTabSel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfTabSel As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfActionName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfActionName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfActionArg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfActionArg As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnDispatchAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDispatchAction As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''litSoldeBancaire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSoldeBancaire As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''phStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phStatus As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''divStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''litStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litStatus As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''phContenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phContenu As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''btnPeriodToday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPeriodToday As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''litTodayCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTodayCount As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTodayCollecte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTodayCollecte As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTodayRecevoir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTodayRecevoir As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTodayRetard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTodayRetard As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''btnPeriodWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPeriodWeek As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''litWeekCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litWeekCount As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litWeekCollecte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litWeekCollecte As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litWeekRecevoir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litWeekRecevoir As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litWeekRetard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litWeekRetard As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''btnPeriodMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPeriodMonth As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''litMonthCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMonthCount As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litMonthCollecte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMonthCollecte As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litMonthRecevoir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMonthRecevoir As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litMonthRetard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMonthRetard As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''btnPeriod3M control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPeriod3M As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lit3MCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lit3MCount As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lit3MCollecte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lit3MCollecte As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lit3MRecevoir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lit3MRecevoir As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lit3MRetard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lit3MRetard As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litPeriodeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPeriodeLabel As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''tabCollecte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabCollecte As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''litTabCollecteCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTabCollecteCount As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''tabRecevoir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabRecevoir As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''litTabRecevoirCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTabRecevoirCount As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''tabRetard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabRetard As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''litTabRetardCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTabRetardCount As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''rpItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpItems As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''phEmpty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phEmpty As Global.System.Web.UI.WebControls.PlaceHolder
End Class
