'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfAutoPayHistory

    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents ddlResult As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents tbFromDate As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbToDate As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents ddlMaxRows As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents btnFilter As Global.System.Web.UI.WebControls.Button

    Protected WithEvents pnlList As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents rptHistory As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents pnlEmpty As Global.System.Web.UI.WebControls.Panel

End Class
