'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfApprobations

    '''<summary>litTitle</summary>
    Protected WithEvents litTitle As Global.System.Web.UI.WebControls.Literal
    '''<summary>litLead</summary>
    Protected WithEvents litLead As Global.System.Web.UI.WebControls.Literal

    '''<summary>pnlAlert</summary>
    Protected WithEvents pnlAlert As Global.System.Web.UI.WebControls.Panel
    '''<summary>litAlert</summary>
    Protected WithEvents litAlert As Global.System.Web.UI.WebControls.Literal
    '''<summary>pnlError</summary>
    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel
    '''<summary>litError</summary>
    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal

    '''<summary>litStatWaitLabel</summary>
    Protected WithEvents litStatWaitLabel As Global.System.Web.UI.WebControls.Literal
    '''<summary>litStatWait</summary>
    Protected WithEvents litStatWait As Global.System.Web.UI.WebControls.Literal
    '''<summary>litStatLateLabel</summary>
    Protected WithEvents litStatLateLabel As Global.System.Web.UI.WebControls.Literal
    '''<summary>litStatLate</summary>
    Protected WithEvents litStatLate As Global.System.Web.UI.WebControls.Literal

    '''<summary>ddlEtat</summary>
    Protected WithEvents ddlEtat As Global.System.Web.UI.WebControls.DropDownList
    '''<summary>btnRefresh</summary>
    Protected WithEvents btnRefresh As Global.System.Web.UI.WebControls.Button

    '''<summary>rptApprobations</summary>
    Protected WithEvents rptApprobations As Global.System.Web.UI.WebControls.Repeater

    '''<summary>pnlEmpty</summary>
    Protected WithEvents pnlEmpty As Global.System.Web.UI.WebControls.Panel
    '''<summary>litEmpty</summary>
    Protected WithEvents litEmpty As Global.System.Web.UI.WebControls.Literal
    '''<summary>litEmptyHint</summary>
    Protected WithEvents litEmptyHint As Global.System.Web.UI.WebControls.Literal

End Class
