'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfAutoPayAuthorizations

    '''<summary>pnlAlert</summary>
    Protected WithEvents pnlAlert As Global.System.Web.UI.WebControls.Panel
    '''<summary>litAlert</summary>
    Protected WithEvents litAlert As Global.System.Web.UI.WebControls.Literal
    '''<summary>pnlError</summary>
    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel
    '''<summary>litError</summary>
    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal

    '''<summary>litStatActive</summary>
    Protected WithEvents litStatActive As Global.System.Web.UI.WebControls.Literal
    '''<summary>litStatScheduled</summary>
    Protected WithEvents litStatScheduled As Global.System.Web.UI.WebControls.Literal
    '''<summary>litStatSuccess</summary>
    Protected WithEvents litStatSuccess As Global.System.Web.UI.WebControls.Literal
    '''<summary>litStatTotalAmount</summary>
    Protected WithEvents litStatTotalAmount As Global.System.Web.UI.WebControls.Literal

    '''<summary>chkShowRevoked</summary>
    Protected WithEvents chkShowRevoked As Global.System.Web.UI.WebControls.CheckBox
    '''<summary>btnRefresh</summary>
    Protected WithEvents btnRefresh As Global.System.Web.UI.WebControls.Button

    '''<summary>rptAuth</summary>
    Protected WithEvents rptAuth As Global.System.Web.UI.WebControls.Repeater

    '''<summary>pnlEmpty</summary>
    Protected WithEvents pnlEmpty As Global.System.Web.UI.WebControls.Panel

End Class
