'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfEmployeeEdit

    '''<summary>form1 control.</summary>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>sm1 control.</summary>
    Protected WithEvents sm1 As Global.System.Web.UI.ScriptManager

    '''<summary>litTitle control.</summary>
    Protected WithEvents litTitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>pnlMsg control.</summary>
    Protected WithEvents pnlMsg As Global.System.Web.UI.WebControls.Panel

    '''<summary>litMsg control.</summary>
    Protected WithEvents litMsg As Global.System.Web.UI.WebControls.Literal

    '''<summary>txtNumber control.</summary>
    Protected WithEvents txtNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtDisplay control.</summary>
    Protected WithEvents txtDisplay As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtFirst control.</summary>
    Protected WithEvents txtFirst As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtLast control.</summary>
    Protected WithEvents txtLast As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtJob control.</summary>
    Protected WithEvents txtJob As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtDept control.</summary>
    Protected WithEvents txtDept As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtEmail control.</summary>
    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtPhone control.</summary>
    Protected WithEvents txtPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtMobile control.</summary>
    Protected WithEvents txtMobile As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtCity control.</summary>
    Protected WithEvents txtCity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtHire control.</summary>
    Protected WithEvents txtHire As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtStatus control.</summary>
    Protected WithEvents txtStatus As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtType control.</summary>
    Protected WithEvents txtType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtColor control.</summary>
    Protected WithEvents txtColor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>chkActive control.</summary>
    Protected WithEvents chkActive As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>litMailbox control.</summary>
    Protected WithEvents litMailbox As Global.System.Web.UI.WebControls.Literal

    '''<summary>btnSave control.</summary>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
End Class
