'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfImportView

    Protected WithEvents litHeaderSub As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents pnlWarning As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litWarning As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents pnlContent As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents litId As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litType As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litFileName As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litUploadDate As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litStatus As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litRows As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litModel As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litTokens As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litCost As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents pnlParty As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litPartyTitle As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents gvParty As Global.System.Web.UI.WebControls.GridView

    Protected WithEvents pnlProduct As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents gvProduct As Global.System.Web.UI.WebControls.GridView

End Class
