'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfMailbox

    Protected WithEvents litAddr As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents lbInbox As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents lbSent As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents lbCompose As Global.System.Web.UI.WebControls.LinkButton

    Protected WithEvents pnlBrowse As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents rptInbox As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents rptSent As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents pnlListEmpty As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents pnlReadEmpty As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlRead As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litSubject As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litFrom As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litTo As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litDate As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents pnlAttach As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litAttach As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litBody As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents pnlCompose As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litComposeFrom As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents txtTo As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtCc As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtSubject As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents reBody As Global.Telerik.Web.UI.RadEditor

    Protected WithEvents fuAttach As Global.System.Web.UI.WebControls.FileUpload
    Protected WithEvents btnSend As Global.System.Web.UI.WebControls.Button
    Protected WithEvents pnlSendMsg As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litSendMsg As Global.System.Web.UI.WebControls.Literal

End Class
