'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfNewUser

    '''<summary>form1 control.</summary>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>hfPlan control.</summary>
    Protected WithEvents hfPlan As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>pnlMessage control.</summary>
    Protected WithEvents pnlMessage As Global.System.Web.UI.WebControls.Panel

    '''<summary>litMessage control.</summary>
    Protected WithEvents litMessage As Global.System.Web.UI.WebControls.Literal

    '''<summary>fileDoc control.</summary>
    Protected WithEvents fileDoc As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>btnExtract control.</summary>
    Protected WithEvents btnExtract As Global.System.Web.UI.WebControls.Button

    '''<summary>pnlUpload control.</summary>
    Protected WithEvents pnlUpload As Global.System.Web.UI.WebControls.Panel

    '''<summary>litUpload control.</summary>
    Protected WithEvents litUpload As Global.System.Web.UI.WebControls.Literal

    '''<summary>txtFirstName control.</summary>
    Protected WithEvents txtFirstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtLastName control.</summary>
    Protected WithEvents txtLastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtEmail control.</summary>
    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtPhone control.</summary>
    Protected WithEvents txtPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtNeq control.</summary>
    Protected WithEvents txtNeq As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtLegalName control.</summary>
    Protected WithEvents txtLegalName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtIncorpDate control.</summary>
    Protected WithEvents txtIncorpDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtBusinessNumber control.</summary>
    Protected WithEvents txtBusinessNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtFiscalYearEnd control.</summary>
    Protected WithEvents txtFiscalYearEnd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtTps control.</summary>
    Protected WithEvents txtTps As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtTvq control.</summary>
    Protected WithEvents txtTvq As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtTvh control.</summary>
    Protected WithEvents txtTvh As Global.System.Web.UI.WebControls.TextBox

    '''<summary>btnRestart control.</summary>
    Protected WithEvents btnRestart As Global.System.Web.UI.WebControls.Button

    '''<summary>btnSave control.</summary>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
End Class
