'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class wbfPaymentProcessors

    '''<summary>litTitle control.</summary>
    Protected WithEvents litTitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>litHead control.</summary>
    Protected WithEvents litHead As Global.System.Web.UI.WebControls.Literal

    '''<summary>litSub control.</summary>
    Protected WithEvents litSub As Global.System.Web.UI.WebControls.Literal

    '''<summary>pnlMsg control.</summary>
    Protected WithEvents pnlMsg As Global.System.Web.UI.WebControls.Panel

    '''<summary>litMsg control.</summary>
    Protected WithEvents litMsg As Global.System.Web.UI.WebControls.Literal

    '''<summary>litSquareBadge control.</summary>
    Protected WithEvents litSquareBadge As Global.System.Web.UI.WebControls.Literal

    '''<summary>pnlConnected control.</summary>
    Protected WithEvents pnlConnected As Global.System.Web.UI.WebControls.Panel

    '''<summary>litLblMerchant control.</summary>
    Protected WithEvents litLblMerchant As Global.System.Web.UI.WebControls.Literal

    '''<summary>litMerchant control.</summary>
    Protected WithEvents litMerchant As Global.System.Web.UI.WebControls.Literal

    '''<summary>litLblLocation control.</summary>
    Protected WithEvents litLblLocation As Global.System.Web.UI.WebControls.Literal

    '''<summary>litLocation control.</summary>
    Protected WithEvents litLocation As Global.System.Web.UI.WebControls.Literal

    '''<summary>litLblSince control.</summary>
    Protected WithEvents litLblSince As Global.System.Web.UI.WebControls.Literal

    '''<summary>litSince control.</summary>
    Protected WithEvents litSince As Global.System.Web.UI.WebControls.Literal

    '''<summary>btnReconnect control.</summary>
    Protected WithEvents btnReconnect As Global.System.Web.UI.WebControls.Button

    '''<summary>btnDisconnect control.</summary>
    Protected WithEvents btnDisconnect As Global.System.Web.UI.WebControls.Button

    '''<summary>pnlDisconnected control.</summary>
    Protected WithEvents pnlDisconnected As Global.System.Web.UI.WebControls.Panel

    '''<summary>litSquareIntro control.</summary>
    Protected WithEvents litSquareIntro As Global.System.Web.UI.WebControls.Literal

    '''<summary>btnConnect control.</summary>
    Protected WithEvents btnConnect As Global.System.Web.UI.WebControls.Button

    '''<summary>litSoon control.</summary>
    Protected WithEvents litSoon As Global.System.Web.UI.WebControls.Literal

    '''<summary>litStripeNote control.</summary>
    Protected WithEvents litStripeNote As Global.System.Web.UI.WebControls.Literal

End Class
