'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Settings

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnReload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReload As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''phStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phStatus As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''litStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litStatus As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''tbLegalName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLegalName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''tbTradeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTradeName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''tbNEQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNEQ As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''tbPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPhone As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''tbAddr1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAddr1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''tbAddr2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAddr2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''tbCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCity As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ddProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddProvince As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tbPostal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPostal As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''tbCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCountry As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''tbGST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbGST As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''tbQST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbQST As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ntbGSTRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ntbGSTRate As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''ntbQSTRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ntbQSTRate As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''ddTaxRounding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddTaxRounding As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ddTaxMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddTaxMode As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tbInvPrefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbInvPrefix As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ntbInvNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ntbInvNext As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''tbSupInvPrefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSupInvPrefix As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ntbSupInvNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ntbSupInvNext As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''tbReceiptPrefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbReceiptPrefix As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ntbReceiptNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ntbReceiptNext As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''tbMailFromName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbMailFromName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''tbMailFromEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbMailFromEmail As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''tbSmtpHost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSmtpHost As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ntbSmtpPort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ntbSmtpPort As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''tbSmtpUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSmtpUser As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''tbSmtpPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSmtpPass As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''tbMailSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbMailSignature As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''tbPdfTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPdfTemplate As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''tbLogoPath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLogoPath As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''tbPaymentTerms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPaymentTerms As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''tbInvoiceNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbInvoiceNotes As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ddShowPaidStamp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddShowPaidStamp As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ddEmailAfterPay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddEmailAfterPay As Global.Telerik.Web.UI.RadComboBox
End Class
