'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class wbfReceiptEdit

    '''<summary>ReceiptEdit1 control.</summary>
    Protected WithEvents ReceiptEdit1 As Global.MngConsul.ucReceiptEdit

End Class
