'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class wbfReceiptEditPopup

    '''<summary>form1 control.</summary>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>RadScriptManager1 control.</summary>
    Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>ReceiptEdit1 control.</summary>
    Protected WithEvents ReceiptEdit1 As Global.MngConsul.ucReceiptEdit

End Class
