'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class wbfSupplierPaymentDream

    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
    Protected WithEvents litSupplier As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litDoc As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litAmount As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents txtFirstName As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtLastName As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtAddress As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtCity As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtProvince As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtPostal As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtAccountName As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents ddlAccountType As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtInstitution As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtTransit As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtAccountNumber As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnPay As Global.System.Web.UI.WebControls.Button
End Class
