'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfSupplierPaymentSuccess

    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents litSupplierName As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litDocumentId As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litDate As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litMethod As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litTransactionId As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litFees As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litAmount As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents pnlWarning As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lnkBack As Global.System.Web.UI.WebControls.HyperLink

End Class
