'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfSetting

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnReload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReload As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''phStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phStatus As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''litStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litStatus As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''tsSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tsSettings As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''mpSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpSettings As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''pvCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvCompany As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''rpEntreprise control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpEntreprise As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pnlEmptyEntreprise control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEmptyEntreprise As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pvTaxes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvTaxes As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''rpTaxes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpTaxes As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pnlEmptyTaxes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEmptyTaxes As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pvEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvEmail As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''rpEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpEmail As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pnlEmptyEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEmptyEmail As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pvPdf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvPdf As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''rpPdf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpPdf As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pnlEmptyPdf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEmptyPdf As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pvAccounting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvAccounting As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''rpComptabilite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpComptabilite As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pnlEmptyComptabilite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEmptyComptabilite As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pvBancaire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvBancaire As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''rpBancaire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpBancaire As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pnlEmptyBancaire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEmptyBancaire As Global.System.Web.UI.WebControls.Panel
End Class
