'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfSupplierPaymentChoice

    '''<summary>
    '''form1 control.
    '''</summary>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''litSupplierName control.
    '''</summary>
    Protected WithEvents litSupplierName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litInvoiceNumber control.
    '''</summary>
    Protected WithEvents litInvoiceNumber As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litAmount control.
    '''</summary>
    Protected WithEvents litAmount As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''pnlNoStripe control.
    '''</summary>
    Protected WithEvents pnlNoStripe As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lnkConfigure As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''pnlError control.
    '''</summary>
    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''litError control.
    '''</summary>
    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''pnlBadgeInterac control.
    '''</summary>
    Protected WithEvents pnlBadgeInterac As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''litFeeInterac control.
    '''</summary>
    Protected WithEvents litFeeInterac As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''pnlBadgeAcss control.
    '''</summary>
    Protected WithEvents pnlBadgeAcss As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''litFeeAcss control.
    '''</summary>
    Protected WithEvents litFeeAcss As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''pnlBadgeCard control.
    '''</summary>
    Protected WithEvents pnlBadgeCard As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''litFeeCard control.
    '''</summary>
    Protected WithEvents litFeeCard As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litAmountInvoice control.
    '''</summary>
    Protected WithEvents litAmountInvoice As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''hfSelectedMethod control.
    '''</summary>
    Protected WithEvents hfSelectedMethod As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfAmountToPay control.
    '''</summary>
    Protected WithEvents hfAmountToPay As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnPay control.
    '''</summary>
    Protected WithEvents btnPay As Global.System.Web.UI.WebControls.Button

End Class
