'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfScheduleAutoPay

    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents pnlSuccess As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litSuccess As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents pnlForm As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents litInvoiceInfo As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litRestant As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents rblAuth As Global.System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents tbAutoPayDate As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents btnConfirm As Global.System.Web.UI.WebControls.Button
    Protected WithEvents lnkClose As Global.System.Web.UI.WebControls.HyperLink

End Class
