'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfSupplierStripeOnboarding

    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents litSupplierName As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litSupplierEmail As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents pnlStatusNew As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlStatusPending As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litAcctIdPending As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents pnlStatusActive As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litAcctIdActive As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents pnlStatusRestricted As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litRestrictedMessage As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents pnlModeChoice As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents btnStartOnboarding As Global.System.Web.UI.WebControls.Button
    Protected WithEvents tbInvitationEmail As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnSendInvitation As Global.System.Web.UI.WebControls.Button
    Protected WithEvents pnlInvitationSent As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litInvitationEmailSent As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents btnResumeOnboarding As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnResendInvitation As Global.System.Web.UI.WebControls.Button
    Protected WithEvents lnkBack As Global.System.Web.UI.WebControls.HyperLink

End Class
