'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfStripeWebhookDiagnostic

    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents lnkStripeDashboard As Global.System.Web.UI.WebControls.HyperLink
    Protected WithEvents btnRefresh As Global.System.Web.UI.WebControls.Button
    Protected WithEvents litTotalEvents As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litProcessedEvents As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litProcessedPct As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litFailedEvents As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litFailedPct As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litPendingEvents As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litSkippedEvents As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLastEvent As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents ddlStatus As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlEventType As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlSince As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents btnApply As Global.System.Web.UI.WebControls.Button
    Protected WithEvents litEvents As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents pnlEmpty As Global.System.Web.UI.WebControls.Panel

End Class
