'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfSupplierPaymentSync

    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents litDocumentId As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litSupplierName As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents pnlAlert As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litAlert As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents pnlSessionList As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litSessions As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents pnlEmpty As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents btnRefresh As Global.System.Web.UI.WebControls.Button
    Protected WithEvents lnkClose As Global.System.Web.UI.WebControls.HyperLink

End Class
