'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class [Default]

    '''<summary>Contrôle litHello.</summary>
    Protected WithEvents litHello As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle litTrust.</summary>
    Protected WithEvents litTrust As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle litOwed.</summary>
    Protected WithEvents litOwed As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle litFees.</summary>
    Protected WithEvents litFees As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle litInvariant.</summary>
    Protected WithEvents litInvariant As Global.System.Web.UI.WebControls.Literal
End Class
