'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class SiteMaster

    '''<summary>Contrôle head.</summary>
    Protected WithEvents head As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>Contrôle navDash.</summary>
    Protected WithEvents navDash As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>Contrôle navSup.</summary>
    Protected WithEvents navSup As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>Contrôle navAbonnes.</summary>
    Protected WithEvents navAbonnes As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>Contrôle navEft.</summary>
    Protected WithEvents navEft As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>Contrôle navRec.</summary>
    Protected WithEvents navRec As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>Contrôle navPartenaires.</summary>
    Protected WithEvents navPartenaires As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>Contrôle navUsers.</summary>
    Protected WithEvents navUsers As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>Contrôle navAudit.</summary>
    Protected WithEvents navAudit As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>Contrôle litUser.</summary>
    Protected WithEvents litUser As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle btnLogout.</summary>
    Protected WithEvents btnLogout As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>Contrôle MainContent.</summary>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
