'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class wbfApiKeys

    '''<summary>Contrôle lnkAbonne.</summary>
    Protected WithEvents lnkAbonne As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>Contrôle litAbonne.</summary>
    Protected WithEvents litAbonne As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle pnlNewKey.</summary>
    Protected WithEvents pnlNewKey As Global.System.Web.UI.WebControls.Panel

    '''<summary>Contrôle litNewKey.</summary>
    Protected WithEvents litNewKey As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle pnlError.</summary>
    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel

    '''<summary>Contrôle litError.</summary>
    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle tbLabel.</summary>
    Protected WithEvents tbLabel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle ddlEnv.</summary>
    Protected WithEvents ddlEnv As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>Contrôle btnGenerate.</summary>
    Protected WithEvents btnGenerate As Global.System.Web.UI.WebControls.Button

    '''<summary>Contrôle rptKeys.</summary>
    Protected WithEvents rptKeys As Global.System.Web.UI.WebControls.Repeater

    '''<summary>Contrôle pnlEmpty.</summary>
    Protected WithEvents pnlEmpty As Global.System.Web.UI.WebControls.Panel
End Class
