'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class wbfAbonnes

    '''<summary>Contrôle tbSearch.</summary>
    Protected WithEvents tbSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle ddlStatut.</summary>
    Protected WithEvents ddlStatut As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>Contrôle btnSearch.</summary>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>Contrôle litCount.</summary>
    Protected WithEvents litCount As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle pnlError.</summary>
    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel

    '''<summary>Contrôle litError.</summary>
    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle rptAbonnes.</summary>
    Protected WithEvents rptAbonnes As Global.System.Web.UI.WebControls.Repeater

    '''<summary>Contrôle pnlEmpty.</summary>
    Protected WithEvents pnlEmpty As Global.System.Web.UI.WebControls.Panel
End Class
