'------------------------------------------------------------------------------
' <auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class wbfAudit

    '''<summary>Contrôle pnlError.</summary>
    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel

    '''<summary>Contrôle litError.</summary>
    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle ddlAction.</summary>
    Protected WithEvents ddlAction As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>Contrôle tbSearch.</summary>
    Protected WithEvents tbSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle btnFilter.</summary>
    Protected WithEvents btnFilter As Global.System.Web.UI.WebControls.Button

    '''<summary>Contrôle lnkExportCsv.</summary>
    Protected WithEvents lnkExportCsv As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>Contrôle rpt.</summary>
    Protected WithEvents rpt As Global.System.Web.UI.WebControls.Repeater

    '''<summary>Contrôle pnlEmpty.</summary>
    Protected WithEvents pnlEmpty As Global.System.Web.UI.WebControls.Panel
End Class
