'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class wbfClient

    '''<summary>Contrôle lnkAbonne.</summary>
    Protected WithEvents lnkAbonne As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>Contrôle lnkClients.</summary>
    Protected WithEvents lnkClients As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>Contrôle litCrumbClient.</summary>
    Protected WithEvents litCrumbClient As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle litTitle.</summary>
    Protected WithEvents litTitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle litMeta.</summary>
    Protected WithEvents litMeta As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle btnBack.</summary>
    Protected WithEvents btnBack As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>Contrôle pnlOk.</summary>
    Protected WithEvents pnlOk As Global.System.Web.UI.WebControls.Panel

    '''<summary>Contrôle litOk.</summary>
    Protected WithEvents litOk As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle pnlError.</summary>
    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel

    '''<summary>Contrôle litError.</summary>
    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle ddlType.</summary>
    Protected WithEvents ddlType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>Contrôle ddlStatut.</summary>
    Protected WithEvents ddlStatut As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>Contrôle tbNom.</summary>
    Protected WithEvents tbNom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle tbReference.</summary>
    Protected WithEvents tbReference As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle tbCourriel.</summary>
    Protected WithEvents tbCourriel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle tbTelephone.</summary>
    Protected WithEvents tbTelephone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle tbAdresse1.</summary>
    Protected WithEvents tbAdresse1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle tbAdresse2.</summary>
    Protected WithEvents tbAdresse2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle tbVille.</summary>
    Protected WithEvents tbVille As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle tbProvince.</summary>
    Protected WithEvents tbProvince As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle tbCodePostal.</summary>
    Protected WithEvents tbCodePostal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle tbPays.</summary>
    Protected WithEvents tbPays As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle tbNotes.</summary>
    Protected WithEvents tbNotes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle tbBankInstitution.</summary>
    Protected WithEvents tbBankInstitution As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle tbBankTransit.</summary>
    Protected WithEvents tbBankTransit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle tbBankAccount.</summary>
    Protected WithEvents tbBankAccount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle btnSave.</summary>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>Contrôle btnCancel.</summary>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.HyperLink
End Class
