'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class wbfClients

    '''<summary>Contrôle lnkAbonne.</summary>
    Protected WithEvents lnkAbonne As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>Contrôle litAbonne.</summary>
    Protected WithEvents litAbonne As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle btnNew.</summary>
    Protected WithEvents btnNew As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>Contrôle tbSearch.</summary>
    Protected WithEvents tbSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle ddlStatut.</summary>
    Protected WithEvents ddlStatut As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>Contrôle btnSearch.</summary>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>Contrôle litCount.</summary>
    Protected WithEvents litCount As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle pnlError.</summary>
    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel

    '''<summary>Contrôle litError.</summary>
    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle rptClients.</summary>
    Protected WithEvents rptClients As Global.System.Web.UI.WebControls.Repeater

    '''<summary>Contrôle pnlEmpty.</summary>
    Protected WithEvents pnlEmpty As Global.System.Web.UI.WebControls.Panel

    '''<summary>Contrôle lnkCreateFirst.</summary>
    Protected WithEvents lnkCreateFirst As Global.System.Web.UI.WebControls.HyperLink
End Class
