'------------------------------------------------------------------------------
' <auto-generated>
'------------------------------------------------------------------------------
Option Strict On
Option Explicit On

Partial Public Class wbfDecaissements
    Protected WithEvents lnkAbonne As Global.System.Web.UI.HtmlControls.HtmlAnchor
    Protected WithEvents litAbonne As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents lnkGrandLivre As Global.System.Web.UI.HtmlControls.HtmlAnchor
    Protected WithEvents btnBatch As Global.System.Web.UI.WebControls.Button
    Protected WithEvents pnlOk As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litOk As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents ddlFournisseur As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents hintNone As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    Protected WithEvents tbMontant As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbFrais As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbDescription As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbReference As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents hfIdem As Global.System.Web.UI.WebControls.HiddenField
    Protected WithEvents btnCreate As Global.System.Web.UI.WebControls.Button
    Protected WithEvents ddlStatut As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents tbSearch As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnFilter As Global.System.Web.UI.WebControls.Button
    Protected WithEvents litCount As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents rptPay As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents pnlEmpty As Global.System.Web.UI.WebControls.Panel
End Class
