'------------------------------------------------------------------------------
' <auto-generated>
'------------------------------------------------------------------------------
Option Strict On
Option Explicit On

Partial Public Class wbfEftBatches
    Protected WithEvents btnGenerate As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnExchange As Global.System.Web.UI.WebControls.Button
    Protected WithEvents rptExchange As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents pnlNoExchange As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents pnlOk As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litOk As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents tbClientNumber As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbDataCentre As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbShortName As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbLongName As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbRetInst As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbRetTransit As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbRetAccount As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbCpaDebit As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbCpaCredit As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnSaveOrig As Global.System.Web.UI.WebControls.Button
    Protected WithEvents rptBatches As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents pnlEmpty As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents fuReturn As Global.System.Web.UI.WebControls.FileUpload
    Protected WithEvents btnImport As Global.System.Web.UI.WebControls.Button
    Protected WithEvents rptReturns As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents pnlNoReturns As Global.System.Web.UI.WebControls.Panel
End Class
