'------------------------------------------------------------------------------
' <auto-generated>
'------------------------------------------------------------------------------
Option Strict On
Option Explicit On

Partial Public Class wbfFournisseur
    Protected WithEvents lnkAbonne As Global.System.Web.UI.HtmlControls.HtmlAnchor
    Protected WithEvents lnkList As Global.System.Web.UI.WebControls.HyperLink
    Protected WithEvents litCrumb As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litTitle As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litMeta As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents btnBack As Global.System.Web.UI.WebControls.HyperLink
    Protected WithEvents pnlOk As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litOk As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents ddlType As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlStatut As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents tbNom As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbReference As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbCourriel As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbTelephone As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbAdresse1 As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbAdresse2 As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbVille As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbProvince As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbCodePostal As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbPays As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbNotes As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbBankInstitution As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbBankTransit As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbBankAccount As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.HyperLink
End Class
