'------------------------------------------------------------------------------
' <auto-generated>
'------------------------------------------------------------------------------
Option Strict On
Option Explicit On

Partial Public Class wbfFournisseurs
    Protected WithEvents lnkAbonne As Global.System.Web.UI.HtmlControls.HtmlAnchor
    Protected WithEvents litAbonne As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents btnNew As Global.System.Web.UI.WebControls.HyperLink
    Protected WithEvents tbSearch As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents ddlStatut As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button
    Protected WithEvents litCount As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents rptList As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents pnlEmpty As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents lnkCreateFirst As Global.System.Web.UI.WebControls.HyperLink
End Class
