'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class wbfGrandLivre

    '''<summary>Contrôle lnkAbonne.</summary>
    Protected WithEvents lnkAbonne As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>Contrôle litAbonne.</summary>
    Protected WithEvents litAbonne As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle lnkClients.</summary>
    Protected WithEvents lnkClients As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>Contrôle lnkPaiements.</summary>
    Protected WithEvents lnkPaiements As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>Contrôle pnlOk.</summary>
    Protected WithEvents pnlOk As Global.System.Web.UI.WebControls.Panel

    '''<summary>Contrôle litOk.</summary>
    Protected WithEvents litOk As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle pnlError.</summary>
    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel

    '''<summary>Contrôle litError.</summary>
    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle litSolde.</summary>
    Protected WithEvents litSolde As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle litReserve.</summary>
    Protected WithEvents litReserve As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle litEftIn.</summary>
    Protected WithEvents litEftIn As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle litEftOut.</summary>
    Protected WithEvents litEftOut As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle ddlOperation.</summary>
    Protected WithEvents ddlOperation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>Contrôle tbMontant.</summary>
    Protected WithEvents tbMontant As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle rowFrais.</summary>
    Protected WithEvents rowFrais As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>Contrôle tbFrais.</summary>
    Protected WithEvents tbFrais As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle tbDescription.</summary>
    Protected WithEvents tbDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle hfIdem.</summary>
    Protected WithEvents hfIdem As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>Contrôle btnPost.</summary>
    Protected WithEvents btnPost As Global.System.Web.UI.WebControls.Button

    '''<summary>Contrôle rptJournal.</summary>
    Protected WithEvents rptJournal As Global.System.Web.UI.WebControls.Repeater

    '''<summary>Contrôle pnlEmpty.</summary>
    Protected WithEvents pnlEmpty As Global.System.Web.UI.WebControls.Panel
End Class
