'------------------------------------------------------------------------------
' <auto-generated>
'------------------------------------------------------------------------------
Option Strict On
Option Explicit On

Partial Public Class wbfInterac
    Protected WithEvents litAbonne As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents pnlOk As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litOk As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents ddlDirection As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents litContrepartieLbl As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents ddlContrepartie As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents tbAmount As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbFee As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbEmail As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents tbDesc As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents pnlNoContrepartie As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents btnInitiate As Global.System.Web.UI.WebControls.Button
    Protected WithEvents rptInterac As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents pnlEmpty As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents rptEvents As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents pnlNoEvents As Global.System.Web.UI.WebControls.Panel
End Class
