'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class wbfUtilisateur

    '''<summary>Contrôle litTitle.</summary>
    Protected WithEvents litTitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle litMeta.</summary>
    Protected WithEvents litMeta As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle pnlOk.</summary>
    Protected WithEvents pnlOk As Global.System.Web.UI.WebControls.Panel

    '''<summary>Contrôle litOk.</summary>
    Protected WithEvents litOk As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle pnlError.</summary>
    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel

    '''<summary>Contrôle litError.</summary>
    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle tbPrenom.</summary>
    Protected WithEvents tbPrenom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle tbNom.</summary>
    Protected WithEvents tbNom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle tbEmail.</summary>
    Protected WithEvents tbEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle cbActif.</summary>
    Protected WithEvents cbActif As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>Contrôle cbSuperAdmin.</summary>
    Protected WithEvents cbSuperAdmin As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>Contrôle litPwdLabel.</summary>
    Protected WithEvents litPwdLabel As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle tbPassword.</summary>
    Protected WithEvents tbPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle litPwdHint.</summary>
    Protected WithEvents litPwdHint As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle btnSave.</summary>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
End Class
