'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class wbfWebhooks

    '''<summary>Contrôle lnkAbonne.</summary>
    Protected WithEvents lnkAbonne As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>Contrôle litAbonne.</summary>
    Protected WithEvents litAbonne As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle btnProcess.</summary>
    Protected WithEvents btnProcess As Global.System.Web.UI.WebControls.Button

    '''<summary>Contrôle pnlOk.</summary>
    Protected WithEvents pnlOk As Global.System.Web.UI.WebControls.Panel

    '''<summary>Contrôle litOk.</summary>
    Protected WithEvents litOk As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle pnlError.</summary>
    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel

    '''<summary>Contrôle litError.</summary>
    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal

    '''<summary>Contrôle tbUrl.</summary>
    Protected WithEvents tbUrl As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle tbSecret.</summary>
    Protected WithEvents tbSecret As Global.System.Web.UI.WebControls.TextBox

    '''<summary>Contrôle btnGenSecret.</summary>
    Protected WithEvents btnGenSecret As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>Contrôle cbActive.</summary>
    Protected WithEvents cbActive As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>Contrôle btnSave.</summary>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>Contrôle rptDeliveries.</summary>
    Protected WithEvents rptDeliveries As Global.System.Web.UI.WebControls.Repeater

    '''<summary>Contrôle pnlEmpty.</summary>
    Protected WithEvents pnlEmpty As Global.System.Web.UI.WebControls.Panel
End Class
