SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-- =============================================================
-- T121PlanComptable : noms de comptes multilingues (fr / en / es).
-- NomFr = Nom existant (français). NomEn / NomEs = traductions.
-- Le mapping se fait par NUMÉRO DE COMPTE (clé ASCII stable, identique
-- entre compagnies car le plan est cloné du modèle). Les comptes
-- personnalisés absents du mapping conservent NomFr en repli.
-- Idempotent : colonnes ajoutées si absentes, puis (re)peuplées.
-- =============================================================

IF COL_LENGTH('dbo.T121PlanComptable', 'NomFr') IS NULL
    ALTER TABLE dbo.T121PlanComptable ADD NomFr varchar(200) NULL;
GO
IF COL_LENGTH('dbo.T121PlanComptable', 'NomEn') IS NULL
    ALTER TABLE dbo.T121PlanComptable ADD NomEn varchar(200) NULL;
GO
IF COL_LENGTH('dbo.T121PlanComptable', 'NomEs') IS NULL
    ALTER TABLE dbo.T121PlanComptable ADD NomEs varchar(200) NULL;
GO

-- Base : français = Nom ; anglais/espagnol = Nom (repli, surchargé ci-dessous)
UPDATE dbo.T121PlanComptable
   SET NomFr = [Nom],
       NomEn = [Nom],
       NomEs = [Nom];
GO

-- Traductions par numéro de compte
UPDATE p
   SET NomEn = t.en,
       NomEs = t.es
FROM dbo.T121PlanComptable p
INNER JOIN (VALUES
    ('1000', N'Petty cash', N'Caja chica'),
    ('1010', N'Bank - Chequing account', N'Banco - Cuenta corriente'),
    ('1020', N'Bank - Savings account', N'Banco - Cuenta de ahorro'),
    ('1030', N'Bank - USD account', N'Banco - Cuenta USD'),
    ('1040', N'Bank - Account 2', N'Banco - Cuenta 2'),
    ('1050', N'Undeposited funds', N'Fondos no depositados'),
    ('1100', N'Accounts receivable', N'Cuentas por cobrar'),
    ('1110', N'Allowance for doubtful accounts', N'Provisión para cuentas incobrables'),
    ('1150', N'Notes receivable', N'Documentos por cobrar'),
    ('1160', N'Accrued interest receivable', N'Intereses devengados por cobrar'),
    ('1170', N'Advances to employees', N'Anticipos a empleados'),
    ('1180', N'Advances to shareholders', N'Anticipos a accionistas'),
    ('1190', N'Other receivables', N'Otras cuentas por cobrar'),
    ('1200', N'Merchandise inventory', N'Inventario de mercancías'),
    ('1210', N'Raw materials inventory', N'Inventario de materias primas'),
    ('1220', N'Work-in-process inventory', N'Inventario de productos en proceso'),
    ('1230', N'Finished goods inventory', N'Inventario de productos terminados'),
    ('1240', N'Supplies inventory', N'Inventario de suministros'),
    ('1300', N'Prepaid insurance', N'Seguros pagados por adelantado'),
    ('1310', N'Prepaid rent', N'Alquiler pagado por adelantado'),
    ('1320', N'Office supplies', N'Suministros de oficina'),
    ('1330', N'Prepaid advertising', N'Publicidad pagada por adelantado'),
    ('1340', N'Other prepaid expenses', N'Otros gastos pagados por adelantado'),
    ('1350', N'Prepaid subscriptions', N'Suscripciones pagadas por adelantado'),
    ('1400', N'Temporary investments', N'Inversiones temporales'),
    ('1410', N'Marketable securities', N'Valores negociables'),
    ('1450', N'GST receivable', N'GST por cobrar'),
    ('1460', N'QST receivable', N'QST por cobrar'),
    ('1470', N'HST receivable', N'HST por cobrar'),
    ('1480', N'Instalment payments - income taxes', N'Pagos provisionales - impuestos'),
    ('1500', N'Land', N'Terrenos'),
    ('1510', N'Buildings', N'Edificios'),
    ('1520', N'Leasehold improvements', N'Mejoras en propiedad arrendada'),
    ('1530', N'Furniture and fixtures', N'Mobiliario y accesorios'),
    ('1540', N'Office equipment', N'Equipo de oficina'),
    ('1550', N'Computer equipment', N'Equipo informático'),
    ('1560', N'Machinery and equipment', N'Maquinaria y equipo'),
    ('1570', N'Vehicles', N'Vehículos'),
    ('1580', N'Tools', N'Herramientas'),
    ('1600', N'Accum. deprec. - Buildings', N'Deprec. acum. - Edificios'),
    ('1610', N'Accum. deprec. - Leasehold improv.', N'Deprec. acum. - Mejoras arrend.'),
    ('1620', N'Accum. deprec. - Furniture', N'Deprec. acum. - Mobiliario'),
    ('1630', N'Accum. deprec. - Office equip.', N'Deprec. acum. - Equipo oficina'),
    ('1640', N'Accum. deprec. - Computer equip.', N'Deprec. acum. - Equipo informático'),
    ('1650', N'Accum. deprec. - Machinery', N'Deprec. acum. - Maquinaria'),
    ('1660', N'Accum. deprec. - Vehicles', N'Deprec. acum. - Vehículos'),
    ('1670', N'Accum. deprec. - Tools', N'Deprec. acum. - Herramientas'),
    ('1700', N'Goodwill', N'Plusvalía (Goodwill)'),
    ('1710', N'Patents', N'Patentes'),
    ('1720', N'Trademarks', N'Marcas comerciales'),
    ('1730', N'Licences and rights', N'Licencias y derechos'),
    ('1740', N'Software', N'Software'),
    ('1750', N'Development costs', N'Costos de desarrollo'),
    ('1760', N'Accum. amort. - Intangibles', N'Amort. acum. - Intangibles'),
    ('1800', N'Long-term investments', N'Inversiones a largo plazo'),
    ('1810', N'Investments in companies', N'Participaciones en empresas'),
    ('1820', N'Security deposits', N'Depósitos en garantía'),
    ('1900', N'Long-term loans receivable', N'Préstamos por cobrar LP'),
    ('1910', N'Mortgages receivable', N'Hipotecas por cobrar'),
    ('1920', N'Advances to related companies', N'Anticipos a empresas relacionadas'),
    ('2000', N'Accounts payable', N'Cuentas por pagar'),
    ('2050', N'Visa credit card', N'Tarjeta de crédito Visa'),
    ('2060', N'Mastercard credit card', N'Tarjeta de crédito Mastercard'),
    ('2070', N'Amex credit card', N'Tarjeta de crédito Amex'),
    ('2100', N'Salaries payable', N'Salarios por pagar'),
    ('2110', N'Vacation payable', N'Vacaciones por pagar'),
    ('2120', N'Interest payable', N'Intereses por pagar'),
    ('2130', N'Accrued liabilities', N'Gastos acumulados por pagar'),
    ('2140', N'Dividends payable', N'Dividendos por pagar'),
    ('2200', N'GST payable', N'GST por pagar'),
    ('2210', N'QST payable', N'QST por pagar'),
    ('2220', N'HST payable', N'HST por pagar'),
    ('2230', N'GST/QST - Net amount payable', N'GST/QST - Monto neto por pagar'),
    ('2300', N'Federal income tax withheld', N'Impuesto federal retenido'),
    ('2305', N'Provincial income tax withheld', N'Impuesto provincial retenido'),
    ('2310', N'QPP payable - Employee', N'QPP por pagar - Empleado'),
    ('2315', N'QPP payable - Employer', N'QPP por pagar - Empleador'),
    ('2320', N'EI payable - Employee', N'EI por pagar - Empleado'),
    ('2325', N'EI payable - Employer', N'EI por pagar - Empleador'),
    ('2330', N'QPIP payable - Employee', N'QPIP por pagar - Empleado'),
    ('2335', N'QPIP payable - Employer', N'QPIP por pagar - Empleador'),
    ('2340', N'HSF payable', N'HSF por pagar'),
    ('2345', N'CNESST payable', N'CNESST por pagar'),
    ('2350', N'Other source deductions', N'Otras retenciones en la fuente'),
    ('2360', N'Deferred revenue', N'Ingresos diferidos'),
    ('2370', N'Customer deposits', N'Depósitos de clientes'),
    ('2400', N'Current portion - Bank loan', N'Porción corriente - Préstamo bancario'),
    ('2410', N'Current portion - Mortgage', N'Porción corriente - Hipoteca'),
    ('2420', N'Line of credit', N'Línea de crédito'),
    ('2500', N'Mortgage payable', N'Hipoteca por pagar'),
    ('2510', N'Mortgage payable - Building 2', N'Hipoteca por pagar - Edificio 2'),
    ('2600', N'Term bank loan', N'Préstamo bancario a plazo'),
    ('2610', N'Loan - Vehicle', N'Préstamo - Vehículo'),
    ('2620', N'Loan - Equipment', N'Préstamo - Equipo'),
    ('2630', N'BDC / Investissement Québec loan', N'Préstamo BDC / Investissement Québec'),
    ('2700', N'Bonds payable', N'Bonos por pagar'),
    ('2800', N'Deferred income taxes payable', N'Impuestos diferidos por pagar'),
    ('2900', N'Due to shareholders', N'Adeudado a accionistas'),
    ('2910', N'Due to related companies', N'Adeudado a empresas relacionadas'),
    ('2920', N'Due to directors', N'Adeudado a administradores'),
    ('2930', N'Other long-term debt', N'Otras deudas a largo plazo'),
    ('3000', N'Common shares', N'Acciones ordinarias'),
    ('3010', N'Preferred shares', N'Acciones preferentes'),
    ('3100', N'Owner''s contributions', N'Aportaciones del propietario'),
    ('3110', N'Partners'' contributions', N'Aportaciones de los socios'),
    ('3200', N'Owner''s withdrawals', N'Retiros del propietario'),
    ('3210', N'Dividends declared', N'Dividendos declarados'),
    ('3300', N'Retained earnings', N'Utilidades retenidas'),
    ('3400', N'Net income for the year', N'Utilidad neta del ejercicio'),
    ('3500', N'Contributed surplus', N'Superávit aportado'),
    ('3510', N'Accumulated other comprehensive income', N'Otro resultado integral acumulado'),
    ('4000', N'Product sales', N'Ventas de productos'),
    ('4010', N'Online sales', N'Ventas en línea'),
    ('4020', N'Sales returns and allowances', N'Devoluciones y descuentos sobre ventas'),
    ('4030', N'Sales discounts', N'Descuentos por pronto pago sobre ventas'),
    ('4100', N'Service revenue', N'Ingresos por servicios'),
    ('4110', N'Consulting revenue', N'Ingresos por consultoría'),
    ('4120', N'Training revenue', N'Ingresos por capacitación'),
    ('4130', N'Project revenue', N'Ingresos por proyectos'),
    ('4200', N'Interest income', N'Ingresos por intereses'),
    ('4210', N'Dividend income', N'Ingresos por dividendos'),
    ('4300', N'Rental income', N'Ingresos por alquiler'),
    ('4310', N'Equipment rental income', N'Ingresos por alquiler de equipo'),
    ('4400', N'Gain on disposal of assets', N'Ganancia por venta de activos'),
    ('4410', N'Foreign exchange gain', N'Ganancia cambiaria'),
    ('4420', N'Government grants', N'Subvenciones gubernamentales'),
    ('4430', N'Miscellaneous income', N'Ingresos varios'),
    ('4440', N'Recovery of bad debts', N'Recuperación de cuentas incobrables'),
    ('5000', N'Merchandise purchases', N'Compras de mercancías'),
    ('5010', N'Raw materials purchases', N'Compras de materias primas'),
    ('5020', N'Purchase returns and allowances', N'Devoluciones y descuentos sobre compras'),
    ('5030', N'Purchase discounts', N'Descuentos por pronto pago sobre compras'),
    ('5040', N'Customs duties', N'Derechos de aduana'),
    ('5100', N'Wages - Production', N'Salarios - Producción'),
    ('5110', N'Employee benefits - Production', N'Prestaciones sociales - Producción'),
    ('5120', N'Overtime - Production', N'Horas extra - Producción'),
    ('5200', N'Subcontracting', N'Subcontratación'),
    ('5210', N'External manufacturing services', N'Servicios de fabricación externa'),
    ('5300', N'Freight-in', N'Fletes sobre compras'),
    ('5310', N'Brokerage and handling fees', N'Gastos de correduría y manejo'),
    ('5400', N'Change in inventory', N'Variación de inventarios'),
    ('5410', N'Inventory obsolescence', N'Obsolescencia de inventarios'),
    ('6000', N'Salaries and wages', N'Sueldos y salarios'),
    ('6010', N'Commissions', N'Comisiones'),
    ('6020', N'Bonuses and premiums', N'Bonos y primas'),
    ('6030', N'Employee benefits', N'Prestaciones sociales'),
    ('6040', N'Payroll taxes - QPP employer', N'Cargas sociales - QPP empleador'),
    ('6045', N'Payroll taxes - EI employer', N'Cargas sociales - EI empleador'),
    ('6050', N'Payroll taxes - QPIP employer', N'Cargas sociales - QPIP empleador'),
    ('6055', N'HSF (Health Services Fund)', N'HSF (Fondo de servicios de salud)'),
    ('6060', N'CNESST', N'CNESST'),
    ('6070', N'Vacation pay', N'Pago de vacaciones'),
    ('6080', N'Employee training', N'Capacitación de empleados'),
    ('6090', N'Recruitment', N'Reclutamiento'),
    ('6100', N'Rent', N'Alquiler'),
    ('6110', N'Property and school taxes', N'Impuestos prediales y escolares'),
    ('6120', N'Maintenance and repairs - Premises', N'Mantenimiento y reparaciones - Local'),
    ('6130', N'Electricity and heating', N'Electricidad y calefacción'),
    ('6140', N'Security', N'Seguridad'),
    ('6150', N'Snow removal and grounds maintenance', N'Remoción de nieve y mantenimiento exterior'),
    ('6200', N'Office supplies', N'Suministros de oficina'),
    ('6210', N'Postage and mail', N'Franqueo y correo'),
    ('6220', N'Photocopying and printing', N'Fotocopias e impresión'),
    ('6300', N'Telephone and cellular', N'Teléfono y celular'),
    ('6310', N'Internet', N'Internet'),
    ('6320', N'Software and subscriptions', N'Software y suscripciones'),
    ('6330', N'Web hosting and domains', N'Alojamiento web y dominios'),
    ('6340', N'IT maintenance', N'Mantenimiento informático'),
    ('6400', N'Advertising', N'Publicidad'),
    ('6410', N'Digital marketing', N'Marketing digital'),
    ('6420', N'Website and social media', N'Sitio web y redes sociales'),
    ('6430', N'Promotional materials', N'Material promocional'),
    ('6440', N'Trade shows and exhibitions', N'Ferias y exposiciones'),
    ('6450', N'Donations and sponsorships', N'Donaciones y patrocinios'),
    ('6500', N'Automobile - Fuel', N'Automóvil - Combustible'),
    ('6510', N'Automobile - Maintenance and repair', N'Automóvil - Mantenimiento y reparación'),
    ('6520', N'Automobile - Insurance', N'Automóvil - Seguro'),
    ('6530', N'Automobile - Registration', N'Automóvil - Matriculación'),
    ('6540', N'Automobile - Parking', N'Automóvil - Estacionamiento'),
    ('6550', N'Mileage allowance', N'Reembolso por kilometraje'),
    ('6560', N'Transportation and taxi', N'Transporte y taxi'),
    ('6570', N'Airline and train tickets', N'Boletos de avión y tren'),
    ('6580', N'Accommodation', N'Alojamiento'),
    ('6590', N'Meals and entertainment', N'Comidas y representación'),
    ('6600', N'Accounting fees', N'Honorarios contables'),
    ('6610', N'Audit fees', N'Honorarios de auditoría'),
    ('6620', N'Legal fees', N'Honorarios jurídicos'),
    ('6630', N'Consulting fees', N'Honorarios de consultoría'),
    ('6640', N'Notary fees', N'Honorarios de notario'),
    ('6650', N'Other professional fees', N'Otros honorarios profesionales'),
    ('6700', N'Liability insurance', N'Seguro de responsabilidad civil'),
    ('6710', N'Property insurance', N'Seguro de bienes'),
    ('6720', N'Vehicle insurance', N'Seguro de vehículos'),
    ('6730', N'Life / Disability insurance', N'Seguro de vida / Invalidez'),
    ('6740', N'Errors and omissions insurance', N'Seguro de errores y omisiones'),
    ('6800', N'Depreciation - Buildings', N'Depreciación - Edificios'),
    ('6810', N'Depreciation - Leasehold improv.', N'Depreciación - Mejoras arrend.'),
    ('6820', N'Depreciation - Furniture', N'Depreciación - Mobiliario'),
    ('6830', N'Depreciation - Equipment', N'Depreciación - Equipo'),
    ('6840', N'Depreciation - IT equipment', N'Depreciación - Informática'),
    ('6850', N'Depreciation - Vehicles', N'Depreciación - Vehículos'),
    ('6860', N'Amortization - Intangibles', N'Amortización - Intangibles'),
    ('6900', N'Interest on loans', N'Intereses sobre préstamos'),
    ('6910', N'Interest on mortgage', N'Intereses sobre hipoteca'),
    ('6920', N'Interest on line of credit', N'Intereses sobre línea de crédito'),
    ('6930', N'Bank charges', N'Gastos bancarios'),
    ('6935', N'Credit card fees', N'Comisiones de tarjetas de crédito'),
    ('6940', N'Foreign exchange fees', N'Gastos de cambio'),
    ('6950', N'Bad debts', N'Cuentas incobrables'),
    ('6960', N'Written-off receivables', N'Cuentas canceladas'),
    ('7000', N'Federal income tax', N'Impuesto federal sobre la renta'),
    ('7010', N'Provincial income tax', N'Impuesto provincial sobre la renta'),
    ('7020', N'Capital tax', N'Impuesto sobre el capital'),
    ('7100', N'Deferred income tax expense - Federal', N'Gasto por impuestos diferidos - Federal'),
    ('7110', N'Deferred income tax expense - Provincial', N'Gasto por impuestos diferidos - Provincial'),
    ('7500', N'Extraordinary gains', N'Ganancias extraordinarias'),
    ('7510', N'Gain on debt settlement', N'Ganancia por liquidación de deuda'),
    ('7520', N'Insurance gain', N'Ganancia por seguro'),
    ('7600', N'Extraordinary losses', N'Pérdidas extraordinarias'),
    ('7610', N'Loss on casualty', N'Pérdida por siniestro'),
    ('7620', N'Loss on disposal of assets', N'Pérdida por venta de activos'),
    ('7630', N'Foreign exchange loss', N'Pérdida cambiaria'),
    ('7800', N'Restructuring costs', N'Costos de reestructuración'),
    ('7810', N'Severance pay', N'Indemnizaciones por despido'),
    ('7820', N'Asset impairment', N'Deterioro de activos'),
    ('7830', N'Penalties and fines', N'Penalidades y multas'),
    ('7840', N'Litigation and settlements', N'Litigios y acuerdos')
) AS t(compte, en, es)
    ON LTRIM(RTRIM(p.Compte)) = t.compte;
GO
