'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class EtapesReprise

    '''<summary>litFil</summary>
    Protected WithEvents litFil As Global.System.Web.UI.WebControls.Literal
End Class