'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class HeaderUser

    '''<summary>
    '''pnlTrial control.
    '''</summary>
    Protected WithEvents pnlTrial As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''litTrial control.
    '''</summary>
    Protected WithEvents litTrial As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''pnlSquare control.
    '''</summary>
    Protected WithEvents pnlSquare As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''litSquare control.
    '''</summary>
    Protected WithEvents litSquare As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litLang As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''pnlCompanyPicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCompanyPicker As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''litCompanyLogoPicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litCompanyLogoPicker As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ddlCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCompany As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlCompanyLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCompanyLabel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''litCompanyLogoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litCompanyLogoLabel As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCompanyName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litInitials control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litInitials As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litUserName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litUserRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litUserRole As Global.System.Web.UI.WebControls.Literal
End Class
