'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class ImportApideckBouton

    '''<summary>spanEtat</summary>
    Protected WithEvents spanEtat As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>litEtat</summary>
    Protected WithEvents litEtat As Global.System.Web.UI.WebControls.Literal

    '''<summary>pnlDate</summary>
    Protected WithEvents pnlDate As Global.System.Web.UI.WebControls.Panel

    '''<summary>txtDate</summary>
    Protected WithEvents txtDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>ddlFrequence</summary>
    Protected WithEvents ddlFrequence As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>btnImporter</summary>
    Protected WithEvents btnImporter As Global.System.Web.UI.WebControls.Button

    '''<summary>hlLiaison</summary>
    Protected WithEvents hlLiaison As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>litResultat</summary>
    Protected WithEvents litResultat As Global.System.Web.UI.WebControls.Literal
End Class
