'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class ImportDonnees

    '''<summary>litIcone</summary>
    Protected WithEvents litIcone As Global.System.Web.UI.WebControls.Literal

    '''<summary>litTitre</summary>
    Protected WithEvents litTitre As Global.System.Web.UI.WebControls.Literal

    '''<summary>litSousTitre</summary>
    Protected WithEvents litSousTitre As Global.System.Web.UI.WebControls.Literal

    '''<summary>litIntro</summary>
    Protected WithEvents litIntro As Global.System.Web.UI.WebControls.Literal

    '''<summary>pnlSucces</summary>
    Protected WithEvents pnlSucces As Global.System.Web.UI.WebControls.Panel

    '''<summary>litSucces</summary>
    Protected WithEvents litSucces As Global.System.Web.UI.WebControls.Literal

    '''<summary>pnlAvert</summary>
    Protected WithEvents pnlAvert As Global.System.Web.UI.WebControls.Panel

    '''<summary>litAvert</summary>
    Protected WithEvents litAvert As Global.System.Web.UI.WebControls.Literal

    '''<summary>pnlErreur</summary>
    Protected WithEvents pnlErreur As Global.System.Web.UI.WebControls.Panel

    '''<summary>litErreur</summary>
    Protected WithEvents litErreur As Global.System.Web.UI.WebControls.Literal

    '''<summary>pnlResultat</summary>
    Protected WithEvents pnlResultat As Global.System.Web.UI.WebControls.Panel

    '''<summary>litResTitre</summary>
    Protected WithEvents litResTitre As Global.System.Web.UI.WebControls.Literal

    '''<summary>litOrigine</summary>
    Protected WithEvents litOrigine As Global.System.Web.UI.WebControls.Literal

    '''<summary>litChips</summary>
    Protected WithEvents litChips As Global.System.Web.UI.WebControls.Literal

    '''<summary>litLignes</summary>
    Protected WithEvents litLignes As Global.System.Web.UI.WebControls.Literal

    '''<summary>btnCreer</summary>
    Protected WithEvents btnCreer As Global.System.Web.UI.WebControls.Button

    '''<summary>hlListe</summary>
    Protected WithEvents hlListe As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>btnAbandonner</summary>
    Protected WithEvents btnAbandonner As Global.System.Web.UI.WebControls.Button

    '''<summary>ucSource</summary>
    Protected WithEvents ucSource As Global.MngConsul.SourceDonnees

    '''<summary>litUn</summary>
    Protected WithEvents litUn As Global.System.Web.UI.WebControls.Literal

    '''<summary>fuFichier</summary>
    Protected WithEvents fuFichier As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>pnlEnMemoire</summary>
    Protected WithEvents pnlEnMemoire As Global.System.Web.UI.WebControls.Panel

    '''<summary>litEnMemoire</summary>
    Protected WithEvents litEnMemoire As Global.System.Web.UI.WebControls.Literal

    '''<summary>btnApercu</summary>
    Protected WithEvents btnApercu As Global.System.Web.UI.WebControls.Button

    '''<summary>btnIA</summary>
    Protected WithEvents btnIA As Global.System.Web.UI.WebControls.Button

    '''<summary>btnLire</summary>
    Protected WithEvents btnLire As Global.System.Web.UI.WebControls.Button

    '''<summary>pnlApercu</summary>
    Protected WithEvents pnlApercu As Global.System.Web.UI.WebControls.Panel

    '''<summary>litApercu</summary>
    Protected WithEvents litApercu As Global.System.Web.UI.WebControls.Literal

    '''<summary>pnlFichiers</summary>
    Protected WithEvents pnlFichiers As Global.System.Web.UI.WebControls.Panel

    '''<summary>gvFichiers</summary>
    Protected WithEvents gvFichiers As Global.System.Web.UI.WebControls.GridView
End Class
