'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class SourceDonnees

    '''<summary>litNumero</summary>
    Protected WithEvents litNumero As Global.System.Web.UI.WebControls.Literal

    '''<summary>ddlSysteme</summary>
    Protected WithEvents ddlSysteme As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>ddlSeparateur</summary>
    Protected WithEvents ddlSeparateur As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>ddlEncodage</summary>
    Protected WithEvents ddlEncodage As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>litNomSysteme</summary>
    Protected WithEvents litNomSysteme As Global.System.Web.UI.WebControls.Literal

    '''<summary>litCheminExport</summary>
    Protected WithEvents litCheminExport As Global.System.Web.UI.WebControls.Literal

    '''<summary>litAideTitre</summary>
    Protected WithEvents litAideTitre As Global.System.Web.UI.WebControls.Literal

    '''<summary>pnlAideSysteme</summary>
    Protected WithEvents pnlAideSysteme As Global.System.Web.UI.WebControls.Panel

    '''<summary>litAideCorps</summary>
    Protected WithEvents litAideCorps As Global.System.Web.UI.WebControls.Literal

    '''<summary>pnlAideAbsente</summary>
    Protected WithEvents pnlAideAbsente As Global.System.Web.UI.WebControls.Panel

    '''<summary>litAideAbsente</summary>
    Protected WithEvents litAideAbsente As Global.System.Web.UI.WebControls.Literal

    '''<summary>pnlColonnes</summary>
    Protected WithEvents pnlColonnes As Global.System.Web.UI.WebControls.Panel

    '''<summary>litColonnes</summary>
    Protected WithEvents litColonnes As Global.System.Web.UI.WebControls.Literal
End Class
