'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class ucReceiptEdit

    '''<summary>rapReceipt control.</summary>
    Protected WithEvents rapReceipt As Global.Telerik.Web.UI.RadAjaxPanel

    '''<summary>RadAjaxLoadingPanel1 control.</summary>
    Protected WithEvents RadAjaxLoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel

    '''<summary>pnlMain control.</summary>
    Protected WithEvents pnlMain As Global.System.Web.UI.WebControls.Panel

    '''<summary>lblPostedBadge control.</summary>
    Protected WithEvents lblPostedBadge As Global.System.Web.UI.WebControls.Label

    '''<summary>lblTiersLabel control.</summary>
    Protected WithEvents lblTiersLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>lblCustomer control.</summary>
    Protected WithEvents lblCustomer As Global.System.Web.UI.WebControls.Label

    '''<summary>rdLabel control.</summary>
    Protected WithEvents rdLabel As Global.Telerik.Web.UI.RadLabel

    '''<summary>litDateLabel control.</summary>
    Protected WithEvents litDateLabel As Global.System.Web.UI.WebControls.Literal

    '''<summary>dpDateEncaissement control.</summary>
    Protected WithEvents dpDateEncaissement As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>litTypeReglLabel control.</summary>
    Protected WithEvents litTypeReglLabel As Global.System.Web.UI.WebControls.Literal

    '''<summary>cbTypeReglement control.</summary>
    Protected WithEvents cbTypeReglement As Global.Telerik.Web.UI.RadComboBox

    '''<summary>litReferenceLabel control.</summary>
    Protected WithEvents litReferenceLabel As Global.System.Web.UI.WebControls.Literal

    '''<summary>txtReference control.</summary>
    Protected WithEvents txtReference As Global.Telerik.Web.UI.RadTextBox

    '''<summary>litComptabiliseLabel control.</summary>
    Protected WithEvents litComptabiliseLabel As Global.System.Web.UI.WebControls.Literal

    '''<summary>chkPost control.</summary>
    Protected WithEvents chkPost As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>litCompteBanqueLabel control.</summary>
    Protected WithEvents litCompteBanqueLabel As Global.System.Web.UI.WebControls.Literal

    '''<summary>lblBank control.</summary>
    Protected WithEvents lblBank As Global.System.Web.UI.WebControls.Label

    '''<summary>hidBankCompte control.</summary>
    Protected WithEvents hidBankCompte As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>lblMontantLabel control.</summary>
    Protected WithEvents lblMontantLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>txtMontantRecu control.</summary>
    Protected WithEvents txtMontantRecu As Global.Telerik.Web.UI.RadTextBox

    '''<summary>litLignesTitle control.</summary>
    Protected WithEvents litLignesTitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>btnAutoImpute control.</summary>
    Protected WithEvents btnAutoImpute As Global.Telerik.Web.UI.RadButton

    '''<summary>litColNoFacture control.</summary>
    Protected WithEvents litColNoFacture As Global.System.Web.UI.WebControls.Literal

    '''<summary>litColDate control.</summary>
    Protected WithEvents litColDate As Global.System.Web.UI.WebControls.Literal

    '''<summary>litColTotal control.</summary>
    Protected WithEvents litColTotal As Global.System.Web.UI.WebControls.Literal

    '''<summary>litColDejaRecu control.</summary>
    Protected WithEvents litColDejaRecu As Global.System.Web.UI.WebControls.Literal

    '''<summary>litColReste control.</summary>
    Protected WithEvents litColReste As Global.System.Web.UI.WebControls.Literal

    '''<summary>litColAImputer control.</summary>
    Protected WithEvents litColAImputer As Global.System.Web.UI.WebControls.Literal

    '''<summary>rpInvoices control.</summary>
    Protected WithEvents rpInvoices As Global.System.Web.UI.WebControls.Repeater

    '''<summary>litTotalDuLabel control.</summary>
    Protected WithEvents litTotalDuLabel As Global.System.Web.UI.WebControls.Literal

    '''<summary>lblTotalDu control.</summary>
    Protected WithEvents lblTotalDu As Global.System.Web.UI.WebControls.Label

    '''<summary>litTotalImputeLabel control.</summary>
    Protected WithEvents litTotalImputeLabel As Global.System.Web.UI.WebControls.Literal

    '''<summary>lblTotalImpute control.</summary>
    Protected WithEvents lblTotalImpute As Global.System.Web.UI.WebControls.Label

    '''<summary>litLabelDiff control.</summary>
    Protected WithEvents litLabelDiff As Global.System.Web.UI.WebControls.Literal

    '''<summary>lblDiff control.</summary>
    Protected WithEvents lblDiff As Global.System.Web.UI.WebControls.Label

    '''<summary>radSave control.</summary>
    Protected WithEvents radSave As Global.Telerik.Web.UI.RadButton

    '''<summary>hidSelectedCustomerId control.</summary>
    Protected WithEvents hidSelectedCustomerId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>rlvCustomers control.</summary>
    Protected WithEvents rlvCustomers As Global.Telerik.Web.UI.RadListView

    '''<summary>hidSelectedBankId control.</summary>
    Protected WithEvents hidSelectedBankId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>rlvBanks control.</summary>
    Protected WithEvents rlvBanks As Global.Telerik.Web.UI.RadListView
End Class
