<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Paie60Sec.Tests</RootNamespace>
    <AssemblyName>60secPaie.Tests</AssemblyName>
    <OptionStrict>On</OptionStrict>
    <OptionInfer>On</OptionInfer>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.6.4" />
    <PackageReference Include="MSTest.TestFramework" Version="3.6.4" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Web" />
    <Reference Include="BCrypt.Net-Next">
      <HintPath>..\..\lib\BCrypt.Net-Next.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\60secPaie.Calcul\60secPaie.Calcul.vbproj" />
    <ProjectReference Include="..\60secPaie.Web\60secPaie.Web.vbproj" />
  </ItemGroup>

</Project>
