'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class PagePresentation

    '''<summary>litLangues</summary>
    Protected WithEvents litLangues As Global.System.Web.UI.WebControls.Literal

    '''<summary>lnkEntree</summary>
    Protected WithEvents lnkEntree As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>lnkAction</summary>
    Protected WithEvents lnkAction As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>lnkAppel</summary>
    Protected WithEvents lnkAppel As Global.System.Web.UI.WebControls.HyperLink
End Class