'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfAdminEdit

    '''<summary>form1 control.</summary>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>RadScriptManager1 control.</summary>
    Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>litTitle control.</summary>
    Protected WithEvents litTitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>btnDelete control.</summary>
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button

    '''<summary>lnkBack control.</summary>
    Protected WithEvents lnkBack As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>btnSave control.</summary>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>pnlMsg control.</summary>
    Protected WithEvents pnlMsg As Global.System.Web.UI.WebControls.Panel

    '''<summary>pMsg control.</summary>
    Protected WithEvents pMsg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>hfId control.</summary>
    Protected WithEvents hfId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>txtEmail control.</summary>
    Protected WithEvents txtEmail As Global.Telerik.Web.UI.RadTextBox

    '''<summary>txtFirstName control.</summary>
    Protected WithEvents txtFirstName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>txtLastName control.</summary>
    Protected WithEvents txtLastName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>litPasswordLabel control.</summary>
    Protected WithEvents litPasswordLabel As Global.System.Web.UI.WebControls.Literal

    '''<summary>txtPassword control.</summary>
    Protected WithEvents txtPassword As Global.Telerik.Web.UI.RadTextBox

    '''<summary>litPasswordHint control.</summary>
    Protected WithEvents litPasswordHint As Global.System.Web.UI.WebControls.Literal

    '''<summary>txtPasswordConfirm control.</summary>
    Protected WithEvents txtPasswordConfirm As Global.Telerik.Web.UI.RadTextBox

    '''<summary>cbActive control.</summary>
    Protected WithEvents cbActive As Global.System.Web.UI.WebControls.CheckBox
End Class
