'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfCompanyEdit

    '''<summary>form1 control.</summary>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>RadScriptManager1 control.</summary>
    Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>litTitle control.</summary>
    Protected WithEvents litTitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>lnkBack control.</summary>
    Protected WithEvents lnkBack As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>btnSave control.</summary>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>pnlMsg control.</summary>
    Protected WithEvents pnlMsg As Global.System.Web.UI.WebControls.Panel

    '''<summary>pMsg control.</summary>
    Protected WithEvents pMsg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>hfGuid control.</summary>
    Protected WithEvents hfGuid As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>hfSubId control.</summary>
    Protected WithEvents hfSubId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>hfOrigName control.</summary>
    Protected WithEvents hfOrigName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>txtName control.</summary>
    Protected WithEvents txtName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>txtLegalName control.</summary>
    Protected WithEvents txtLegalName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>txtCode control.</summary>
    Protected WithEvents txtCode As Global.Telerik.Web.UI.RadTextBox

    '''<summary>txtStructure control.</summary>
    Protected WithEvents txtStructure As Global.Telerik.Web.UI.RadTextBox

    '''<summary>txtNEQ control.</summary>
    Protected WithEvents txtNEQ As Global.Telerik.Web.UI.RadTextBox

    '''<summary>txtBusinessNumber control.</summary>
    Protected WithEvents txtBusinessNumber As Global.Telerik.Web.UI.RadTextBox

    '''<summary>ddlPlan control.</summary>
    Protected WithEvents ddlPlan As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>ddlStatus control.</summary>
    Protected WithEvents ddlStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>txtAmount control.</summary>
    Protected WithEvents txtAmount As Global.Telerik.Web.UI.RadTextBox

    '''<summary>ddlCurrency control.</summary>
    Protected WithEvents ddlCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>ddlCycle control.</summary>
    Protected WithEvents ddlCycle As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>cbTrial control.</summary>
    Protected WithEvents cbTrial As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>txtStartDate control.</summary>
    Protected WithEvents txtStartDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtNextBilling control.</summary>
    Protected WithEvents txtNextBilling As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtEndDate control.</summary>
    Protected WithEvents txtEndDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtTrialEnd control.</summary>
    Protected WithEvents txtTrialEnd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>litConfirmName control.</summary>
    Protected WithEvents litConfirmName As Global.System.Web.UI.WebControls.Literal

    '''<summary>txtConfirmDelete control.</summary>
    Protected WithEvents txtConfirmDelete As Global.System.Web.UI.WebControls.TextBox

    '''<summary>btnDelete control.</summary>
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button
End Class
