'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfDemoReset

    Protected WithEvents ddlDemo As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents btnReset As Global.System.Web.UI.WebControls.Button
    Protected WithEvents pnlMsg As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litMsg As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents btnSnapshot As Global.System.Web.UI.WebControls.Button
    Protected WithEvents pnlMsgSnap As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litMsgSnap As Global.System.Web.UI.WebControls.Literal

End Class
