'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfJobs

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''ralp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ralp As Global.Telerik.Web.UI.RadAjaxLoadingPanel

    '''<summary>
    '''phStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phStatus As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''divStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''litStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litStatus As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litKpiActifs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litKpiActifs As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litKpiSucces control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litKpiSucces As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litKpiEchecs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litKpiEchecs As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litKpiEnCours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litKpiEnCours As Global.System.Web.UI.WebControls.Literal

    '''<summary>Libellés localisés (convertis de blocs &lt;%= %&gt; pour compatibilité RadAjax).</summary>
    Protected WithEvents litTitre As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litSousTitre As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLblActifs As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLblSucces As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLblEchecs As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLblEnCours As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litListeTitre As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litEmptyText As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litThJob As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litThType As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litThSchedules As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litThProchaine As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litThDerniere As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litThActions As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ddlFiltreActif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFiltreActif As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ddlFiltreType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFiltreType As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtRecherche control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRecherche As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''btnRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefresh As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnNouveau control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNouveau As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''phContenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phContenu As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''phEmpty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phEmpty As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''phTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phTable As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''rpJobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpJobs As Global.System.Web.UI.WebControls.Repeater
End Class
