'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfJobSchedule

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''ralp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ralp As Global.Telerik.Web.UI.RadAjaxLoadingPanel

    '''<summary>
    '''litTitre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTitre As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBadgeJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBadgeJob As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''phStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phStatus As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''divStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''litStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litStatus As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''phPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phPreview As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''divPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPreview As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''litProchaineExec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litProchaineExec As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litProchaineExecMeta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litProchaineExecMeta As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''txtNom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNom As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ddlScheduleType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlScheduleType As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''phChamps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phChamps As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''pnlInterval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInterval As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtIntervalMinutes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIntervalMinutes As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''pnlDaily control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDaily As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''dpHeureDaily control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpHeureDaily As Global.Telerik.Web.UI.RadTimePicker

    '''<summary>
    '''pnlWeekly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlWeekly As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''dpHeureWeekly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpHeureWeekly As Global.Telerik.Web.UI.RadTimePicker

    '''<summary>
    '''cbLun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbLun As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''cbMar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMar As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''cbMer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMer As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''cbJeu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbJeu As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''cbVen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbVen As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''cbSam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSam As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''cbDim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDim As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''pnlMonthly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMonthly As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddlIntervalleMois control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIntervalleMois As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''dpHeureMonthly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpHeureMonthly As Global.Telerik.Web.UI.RadTimePicker

    '''<summary>
    '''ddlJourMois control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlJourMois As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''pnlCron control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCron As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtCronExpression control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCronExpression As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''pnlOnce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOnce As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''dpDateOnce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpDateOnce As Global.Telerik.Web.UI.RadDateTimePicker

    '''<summary>
    '''dpDateDebut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpDateDebut As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''dpDateFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpDateFin As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''ddlEtat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEtat As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtHandlerParams control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHandlerParams As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''hfJobId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfJobId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnApercu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApercu As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnSupprimer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSupprimer As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnAnnuler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAnnuler As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnEnregistrer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEnregistrer As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Literals de localisation (libellés HTML convertis).
    '''</summary>
    Protected WithEvents litLoc01 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc02 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc03 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc04 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc05 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc06 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc07 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc08 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc09 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc10 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc11 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc12 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc13 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc14 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc15 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc16 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc17 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc18 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc19 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc20 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc21 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc22 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc23 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc24 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc25 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc26 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc27 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc28 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc29 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc30 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc31 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc32 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc33 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc34 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc35 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc36 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc37 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc38 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc39 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc40 As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLoc41 As Global.System.Web.UI.WebControls.Literal
End Class
