'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfJobDashboard

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''ralp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ralp As Global.Telerik.Web.UI.RadAjaxLoadingPanel

    '''<summary>
    '''tmrAutoRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tmrAutoRefresh As Global.System.Web.UI.Timer

    '''<summary>
    '''litLastRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litLastRefresh As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''btnRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefresh As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''phContenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phContenu As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''litKpiJobsActifs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litKpiJobsActifs As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litKpiJobsInactifs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litKpiJobsInactifs As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litKpiSucces24h control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litKpiSucces24h As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litKpiTaux7j control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litKpiTaux7j As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litKpiEchecs24h control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litKpiEchecs24h As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litKpiTotal7j control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litKpiTotal7j As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litKpiEnCours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litKpiEnCours As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litKpiDureeMoy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litKpiDureeMoy As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTendance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTendance As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''badgeAlertes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents badgeAlertes As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''phAlertesEmpty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phAlertesEmpty As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''rpAlertes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpAlertes As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''litNbProchaines control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litNbProchaines As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''phProchainesEmpty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phProchainesEmpty As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''rpProchaines control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpProchaines As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''phActiviteEmpty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phActiviteEmpty As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''rpActivite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpActivite As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''litLoc01 control.
    '''</summary>
    Protected WithEvents litLoc01 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc02 control.
    '''</summary>
    Protected WithEvents litLoc02 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc03 control.
    '''</summary>
    Protected WithEvents litLoc03 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc04 control.
    '''</summary>
    Protected WithEvents litLoc04 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc05 control.
    '''</summary>
    Protected WithEvents litLoc05 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc06 control.
    '''</summary>
    Protected WithEvents litLoc06 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc07 control.
    '''</summary>
    Protected WithEvents litLoc07 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc08 control.
    '''</summary>
    Protected WithEvents litLoc08 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc09 control.
    '''</summary>
    Protected WithEvents litLoc09 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc10 control.
    '''</summary>
    Protected WithEvents litLoc10 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc11 control.
    '''</summary>
    Protected WithEvents litLoc11 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc12 control.
    '''</summary>
    Protected WithEvents litLoc12 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc13 control.
    '''</summary>
    Protected WithEvents litLoc13 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc14 control.
    '''</summary>
    Protected WithEvents litLoc14 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc15 control.
    '''</summary>
    Protected WithEvents litLoc15 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc16 control.
    '''</summary>
    Protected WithEvents litLoc16 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc17 control.
    '''</summary>
    Protected WithEvents litLoc17 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc18 control.
    '''</summary>
    Protected WithEvents litLoc18 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc19 control.
    '''</summary>
    Protected WithEvents litLoc19 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc20 control.
    '''</summary>
    Protected WithEvents litLoc20 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc21 control.
    '''</summary>
    Protected WithEvents litLoc21 As Global.System.Web.UI.WebControls.Literal
End Class
