'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfJobMonitoring

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''ralp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ralp As Global.Telerik.Web.UI.RadAjaxLoadingPanel

    '''<summary>
    '''litLoc01 control.
    '''</summary>
    Protected WithEvents litLoc01 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc02 control.
    '''</summary>
    Protected WithEvents litLoc02 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc03 control.
    '''</summary>
    Protected WithEvents litLoc03 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc04 control.
    '''</summary>
    Protected WithEvents litLoc04 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc05 control.
    '''</summary>
    Protected WithEvents litLoc05 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc06 control.
    '''</summary>
    Protected WithEvents litLoc06 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc07 control.
    '''</summary>
    Protected WithEvents litLoc07 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc08 control.
    '''</summary>
    Protected WithEvents litLoc08 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc09 control.
    '''</summary>
    Protected WithEvents litLoc09 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc10 control.
    '''</summary>
    Protected WithEvents litLoc10 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc11 control.
    '''</summary>
    Protected WithEvents litLoc11 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc12 control.
    '''</summary>
    Protected WithEvents litLoc12 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc13 control.
    '''</summary>
    Protected WithEvents litLoc13 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc14 control.
    '''</summary>
    Protected WithEvents litLoc14 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc15 control.
    '''</summary>
    Protected WithEvents litLoc15 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc16 control.
    '''</summary>
    Protected WithEvents litLoc16 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc17 control.
    '''</summary>
    Protected WithEvents litLoc17 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc18 control.
    '''</summary>
    Protected WithEvents litLoc18 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc19 control.
    '''</summary>
    Protected WithEvents litLoc19 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc20 control.
    '''</summary>
    Protected WithEvents litLoc20 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc21 control.
    '''</summary>
    Protected WithEvents litLoc21 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc22 control.
    '''</summary>
    Protected WithEvents litLoc22 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLoc23 control.
    '''</summary>
    Protected WithEvents litLoc23 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litKpiTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litKpiTotal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litKpiSucces control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litKpiSucces As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litKpiSuccesPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litKpiSuccesPct As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litKpiEchecs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litKpiEchecs As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litKpiEchecsPct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litKpiEchecsPct As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litKpiEnCours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litKpiEnCours As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litKpiDureeMoy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litKpiDureeMoy As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ddlJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlJob As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ddlStatut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStatut As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ddlTrigger control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTrigger As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''dpDateDebut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpDateDebut As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''dpDateFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpDateFin As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''btnReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReset As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnFiltrer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFiltrer As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''phContenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phContenu As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''phEmpty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phEmpty As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''phTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phTable As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''rpExecutions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpExecutions As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''litPagInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPagInfo As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''btnPagPrev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPagPrev As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''litPagPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPagPages As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''btnPagNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPagNext As Global.System.Web.UI.WebControls.LinkButton
End Class
