'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfMailAccounts

    '''<summary>tbSearch control.</summary>
    Protected WithEvents tbSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>btnSearch control.</summary>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>btnClear control.</summary>
    Protected WithEvents btnClear As Global.System.Web.UI.WebControls.Button

    '''<summary>rlvAccounts control.</summary>
    Protected WithEvents rlvAccounts As Global.Telerik.Web.UI.RadListView

    '''<summary>rlvSystem control.</summary>
    Protected WithEvents rlvSystem As Global.Telerik.Web.UI.RadListView

    '''<summary>litRenameCompany control.</summary>
    Protected WithEvents litRenameCompany As Global.System.Web.UI.WebControls.Literal

    '''<summary>hfRenameGuid control.</summary>
    Protected WithEvents hfRenameGuid As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>tbRenameLocal control.</summary>
    Protected WithEvents tbRenameLocal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>lblRenameMsg control.</summary>
    Protected WithEvents lblRenameMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>btnSaveRename control.</summary>
    Protected WithEvents btnSaveRename As Global.System.Web.UI.WebControls.Button

    '''<summary>litPwdAddr control.</summary>
    Protected WithEvents litPwdAddr As Global.System.Web.UI.WebControls.Literal

    '''<summary>hfPwdEmail control.</summary>
    Protected WithEvents hfPwdEmail As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>tbPwd control.</summary>
    Protected WithEvents tbPwd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>lblPwdMsg control.</summary>
    Protected WithEvents lblPwdMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>btnSavePwd control.</summary>
    Protected WithEvents btnSavePwd As Global.System.Web.UI.WebControls.Button

    '''<summary>btnRemovePwd control.</summary>
    Protected WithEvents btnRemovePwd As Global.System.Web.UI.WebControls.Button
End Class
