'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class wbfPlanComptableDefaut

    '''<summary>litMsg</summary>
    Protected WithEvents litMsg As Global.System.Web.UI.WebControls.Literal

    '''<summary>litNbComptes</summary>
    Protected WithEvents litNbComptes As Global.System.Web.UI.WebControls.Literal

    '''<summary>litNbActifs</summary>
    Protected WithEvents litNbActifs As Global.System.Web.UI.WebControls.Literal

    '''<summary>litNbSysteme</summary>
    Protected WithEvents litNbSysteme As Global.System.Web.UI.WebControls.Literal

    '''<summary>litNbClasses</summary>
    Protected WithEvents litNbClasses As Global.System.Web.UI.WebControls.Literal

    '''<summary>txtSearch</summary>
    Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>btnSearch</summary>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>btnTout</summary>
    Protected WithEvents btnTout As Global.System.Web.UI.WebControls.Button

    '''<summary>litTableau</summary>
    Protected WithEvents litTableau As Global.System.Web.UI.WebControls.Literal

    '''<summary>litTitreForm</summary>
    Protected WithEvents litTitreForm As Global.System.Web.UI.WebControls.Literal

    '''<summary>hfId</summary>
    Protected WithEvents hfId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>ddlClasseParent</summary>
    Protected WithEvents ddlClasseParent As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>ddlClasse</summary>
    Protected WithEvents ddlClasse As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>txtNumero</summary>
    Protected WithEvents txtNumero As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtNom</summary>
    Protected WithEvents txtNom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>ddlTypeBilan</summary>
    Protected WithEvents ddlTypeBilan As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>ddlSens</summary>
    Protected WithEvents ddlSens As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>chkActif</summary>
    Protected WithEvents chkActif As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>txtDescription</summary>
    Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>btnSave</summary>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>btnAnnuler</summary>
    Protected WithEvents btnAnnuler As Global.System.Web.UI.WebControls.Button
End Class
