'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfPlaidDiagnostic

    Protected WithEvents lnkPlaidDashboard As Global.System.Web.UI.WebControls.HyperLink
    Protected WithEvents btnRefresh As Global.System.Web.UI.WebControls.Button
    Protected WithEvents litActiveAccounts As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litTotalAccounts As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litItems As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litCompanies As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litBanks As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litErrors As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents litLastBalance As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents ddlStatus As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents ddlSince As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents btnApply As Global.System.Web.UI.WebControls.Button
    Protected WithEvents litAccounts As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents pnlAccountsEmpty As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents litSyncLog As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents pnlLogEmpty As Global.System.Web.UI.WebControls.Panel

End Class
