'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class wbfPaieAnnees

    '''<summary>btnCreer control.</summary>
    Protected WithEvents btnCreer As Global.System.Web.UI.WebControls.Button

    '''<summary>pnlMsg control.</summary>
    Protected WithEvents pnlMsg As Global.System.Web.UI.WebControls.Panel

    '''<summary>pMsg control.</summary>
    Protected WithEvents pMsg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>rptAnnees control.</summary>
    Protected WithEvents rptAnnees As Global.System.Web.UI.WebControls.Repeater

    '''<summary>lblAucune control.</summary>
    Protected WithEvents lblAucune As Global.System.Web.UI.WebControls.Label
End Class
