'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class wbfPlanComptableDefaut

    '''<summary>litMsg</summary>
    Protected WithEvents litMsg As Global.System.Web.UI.WebControls.Literal

    '''<summary>litNbComptes</summary>
    Protected WithEvents litNbComptes As Global.System.Web.UI.WebControls.Literal

    '''<summary>litNbActifs</summary>
    Protected WithEvents litNbActifs As Global.System.Web.UI.WebControls.Literal

    '''<summary>litNbSysteme</summary>
    Protected WithEvents litNbSysteme As Global.System.Web.UI.WebControls.Literal

    '''<summary>litNbClasses</summary>
    Protected WithEvents litNbClasses As Global.System.Web.UI.WebControls.Literal

    '''<summary>txtSearch</summary>
    Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>btnSearch</summary>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>btnTout</summary>
    Protected WithEvents btnTout As Global.System.Web.UI.WebControls.Button

    '''<summary>litTableau</summary>
    Protected WithEvents litTableau As Global.System.Web.UI.WebControls.Literal

    '''<summary>carteOverlay</summary>
    Protected WithEvents carteOverlay As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>carteCompte</summary>
    Protected WithEvents carteCompte As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>litTitreForm</summary>
    Protected WithEvents litTitreForm As Global.System.Web.UI.WebControls.Literal

    '''<summary>hfId</summary>
    Protected WithEvents hfId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>ddlClasseParent</summary>
    Protected WithEvents ddlClasseParent As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>ddlClasse</summary>
    Protected WithEvents ddlClasse As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>txtNumero</summary>
    Protected WithEvents txtNumero As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtNom</summary>
    Protected WithEvents txtNom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>ddlTypeBilan</summary>
    Protected WithEvents ddlTypeBilan As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>ddlSens</summary>
    Protected WithEvents ddlSens As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>chkActif</summary>
    Protected WithEvents chkActif As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>txtDescription</summary>
    Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>pnlAlias</summary>
    Protected WithEvents pnlAlias As Global.System.Web.UI.WebControls.Panel

    '''<summary>litAliases</summary>
    Protected WithEvents litAliases As Global.System.Web.UI.WebControls.Literal

    '''<summary>ddlAliasLangue</summary>
    Protected WithEvents ddlAliasLangue As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>txtAliasNom</summary>
    Protected WithEvents txtAliasNom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtAliasSousType</summary>
    Protected WithEvents txtAliasSousType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>btnAjouterAlias</summary>
    Protected WithEvents btnAjouterAlias As Global.System.Web.UI.WebControls.Button

    '''<summary>btnTraduireAlias</summary>
    Protected WithEvents btnTraduireAlias As Global.System.Web.UI.WebControls.Button

    '''<summary>btnTraduireTous</summary>
    Protected WithEvents btnTraduireTous As Global.System.Web.UI.WebControls.Button

    '''<summary>btnSave</summary>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>btnAnnuler</summary>
    Protected WithEvents btnAnnuler As Global.System.Web.UI.WebControls.Button

    '''<summary>ddlCompagnie</summary>
    Protected WithEvents ddlCompagnie As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>ddlFiltreCandidats</summary>
    Protected WithEvents ddlFiltreCandidats As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>btnVoir</summary>
    Protected WithEvents btnVoir As Global.System.Web.UI.WebControls.Button

    '''<summary>litCandidats</summary>
    Protected WithEvents litCandidats As Global.System.Web.UI.WebControls.Literal

    '''<summary>btnAjouterModele</summary>
    Protected WithEvents btnAjouterModele As Global.System.Web.UI.WebControls.Button

    '''<summary>ddlCieResync</summary>
    Protected WithEvents ddlCieResync As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>chkSupprimerEnTrop</summary>
    Protected WithEvents chkSupprimerEnTrop As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>btnSimulerResync</summary>
    Protected WithEvents btnSimulerResync As Global.System.Web.UI.WebControls.Button

    '''<summary>btnAppliquerResync</summary>
    Protected WithEvents btnAppliquerResync As Global.System.Web.UI.WebControls.Button

    '''<summary>litResync</summary>
    Protected WithEvents litResync As Global.System.Web.UI.WebControls.Literal
End Class
