'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfPlanEdit

    '''<summary>form1 control.</summary>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>RadScriptManager1 control.</summary>
    Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>litTitle control.</summary>
    Protected WithEvents litTitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>btnDelete control.</summary>
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button

    '''<summary>lnkBack control.</summary>
    Protected WithEvents lnkBack As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>btnSave control.</summary>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>pnlMsg control.</summary>
    Protected WithEvents pnlMsg As Global.System.Web.UI.WebControls.Panel

    '''<summary>pMsg control.</summary>
    Protected WithEvents pMsg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>hfId control.</summary>
    Protected WithEvents hfId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>txtCode control.</summary>
    Protected WithEvents txtCode As Global.Telerik.Web.UI.RadTextBox

    '''<summary>txtName control.</summary>
    Protected WithEvents txtName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>txtTagline control.</summary>
    Protected WithEvents txtTagline As Global.Telerik.Web.UI.RadTextBox

    '''<summary>txtDescription control.</summary>
    Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>reDescriptionLong control.</summary>
    Protected WithEvents reDescriptionLong As Global.Telerik.Web.UI.RadEditor

    '''<summary>txtAmount control.</summary>
    Protected WithEvents txtAmount As Global.Telerik.Web.UI.RadTextBox

    '''<summary>ddlCurrency control.</summary>
    Protected WithEvents ddlCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>ddlBillingCycle control.</summary>
    Protected WithEvents ddlBillingCycle As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>txtTrialDays control.</summary>
    Protected WithEvents txtTrialDays As Global.Telerik.Web.UI.RadTextBox

    '''<summary>txtDisplayOrder control.</summary>
    Protected WithEvents txtDisplayOrder As Global.Telerik.Web.UI.RadTextBox

    '''<summary>txtProcessorName control.</summary>
    Protected WithEvents txtProcessorName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>txtStripeProductId control.</summary>
    Protected WithEvents txtStripeProductId As Global.Telerik.Web.UI.RadTextBox

    '''<summary>txtStripePriceId control.</summary>
    Protected WithEvents txtStripePriceId As Global.Telerik.Web.UI.RadTextBox

    '''<summary>txtMaxUsers control.</summary>
    Protected WithEvents txtMaxUsers As Global.Telerik.Web.UI.RadTextBox

    '''<summary>txtMaxClients control.</summary>
    Protected WithEvents txtMaxClients As Global.Telerik.Web.UI.RadTextBox

    '''<summary>txtMaxDocuments control.</summary>
    Protected WithEvents txtMaxDocuments As Global.Telerik.Web.UI.RadTextBox

    '''<summary>txtMaxStorageMB control.</summary>
    Protected WithEvents txtMaxStorageMB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>txtEmployeeRange control.</summary>
    Protected WithEvents txtEmployeeRange As Global.Telerik.Web.UI.RadTextBox

    '''<summary>txtBadgeText control.</summary>
    Protected WithEvents txtBadgeText As Global.Telerik.Web.UI.RadTextBox

    '''<summary>cbRecommended control.</summary>
    Protected WithEvents cbRecommended As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>cbActive control.</summary>
    Protected WithEvents cbActive As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>txtFeatures control.</summary>
    Protected WithEvents txtFeatures As Global.System.Web.UI.WebControls.TextBox
End Class
