'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfPlans

    '''<summary>
    '''RadAjaxLoadingPanel1 control.
    '''</summary>
    Protected WithEvents RadAjaxLoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel

    '''<summary>
    '''rwmPlans control.
    '''</summary>
    Protected WithEvents rwmPlans As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''rwPlan control.
    '''</summary>
    Protected WithEvents rwPlan As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''Ram1 control.
    '''</summary>
    Protected WithEvents Ram1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''btnAddPlan control.
    '''</summary>
    Protected WithEvents btnAddPlan As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbSearch control.
    '''</summary>
    Protected WithEvents tbSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearch control.
    '''</summary>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnClear control.
    '''</summary>
    Protected WithEvents btnClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rlvPlans control.
    '''</summary>
    Protected WithEvents rlvPlans As Global.Telerik.Web.UI.RadListView
End Class
