'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class wbfPaieFormulaires

    Protected WithEvents pnlMsg As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents pMsg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    Protected WithEvents ddlAnnee As Global.System.Web.UI.WebControls.DropDownList

    Protected WithEvents ddlType As Global.System.Web.UI.WebControls.DropDownList

    Protected WithEvents fuFichier As Global.System.Web.UI.WebControls.FileUpload

    Protected WithEvents btnTeleverser As Global.System.Web.UI.WebControls.Button

    Protected WithEvents rptFormulaires As Global.System.Web.UI.WebControls.Repeater

    Protected WithEvents lblAucun As Global.System.Web.UI.WebControls.Label
End Class