'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wbfReservations

    Protected WithEvents litNb As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents rpt As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents pnlVide As Global.System.Web.UI.WebControls.Panel
End Class
